// Combined medicines dataset (single + combinations from PDF + base 1000 list)
window.meds_10000 = [];
const allMedsCombined = [
  "(a) Skin Grafting Knife Blade(Sterile) made of carbon steel or stainless steel material 1 5 8 mm long individually wrapped in",
  "a--Sanitary Napkin, Beltless 1 . Covering Covering of the absorbent filler shall be good qualityknitted sleeveor non-",
  "ABDOMINAL DRAINKIT, STERILE, HAVING DRAINAGE CATHETER AND COLLECTION BAG {2 0 0 0 ml } size 2 4",
  "ABDOMINAL DRAINKIT, STERILE, HAVINGDRAINAGECATHETERANDCOLLECTIONBAG {2 0 0 0 ml } size 2 8",
  "ABSORBABLE SURGICALSUTURE { SYNTHETIC } 1/2 Cir RB NIDDLE 2 0 mm LENGTH 7 0 cm",
  "ABSORBABLE SURGICALSUTURE { SYNTHETIC } 1/2 Cir RB NIDDLE 3 0 mm LENGTH 9 0 cm",
  "ABSORBABLE SURGICALSUTURE { SYNTHETIC } 1/2 Cir RB NIDDLE 4 0 mm LENGTH 9 0 cm",
  "ABSORBABLE SURGICALSUTURE { SYNTHETIC } 1/2 Cir TAPERCUT NEEDLE { HEAVY } 4 0 mm LENGTH 9 0 cm",
  "ABSORBABLE SURGICALSUTURE { SYNTHETIC } 3/8 Cir CUTTING NIDDLE 2 2 mm LENGTH 4 5 cm",
  "ABSORBABLE SURGICALSUTURE { SYNTHETIC } {1/2 Cir RB NIDDLE 4 0 mm LENGTH 9 0 cm}",
  "Absorbable Surgical Suture (Synthetic) 3/8 Circle Cutting 1 6 mm Needle, Suture Length 7 0 cm",
  "Absorbent CottonWool I.P. 75 gm(NonSterile) 1's",
  "AbsorbentCottonWoolI . P . 2 0 0 gm(NonSterile) 1 's",
  "AbsorbentgelatinspongeIP 6 6, SIZE 8 0 mm x 5 0 mm x 1 0 mm. should besterilized",
  "ACARBOSE TABLETS IP 50 MG 10's",
  "ACEBROPHYLLINECapsules 100 mg 10's",
  "Aceclofenac + Paracetamol(100 mg + 325 mg) Tablets 10's",
  "Aceclofenac 100 mg + Paracetamol 325 mg + Chorzoxazone 250  mg film coatedtab.",
  "ACECLOFENAC 100 mg + PARACETAMOL 325 mg + SERRATIOPEPTIDASE 15 mg Tablets",
  "Aceclofenac 100 mg Tablets IP 10's",
  "ACECLOFENAC TabletsSR/ CR 200 mg 10's",
  "ACENOCOUMAROL TABLETS 2 MGIP 30's",
  "Acetaminophen + Tramadol Hydrochloride(325 mg + 37.5 mg) filmcoated Tablets",
  "Acetazolamide TabletsI.P 250 mg 10's",
  "Acetyl Salicylic Acid(Aspirin) Tablet I.P 325 mg 14's",
  "ACETYLCYSTEINE Tablets 600 mg 10's",
  "ACICLOVIR INTRAVENOUS INFUSION IP 500 MG/VIAL",
  "Acyclovir",
  "Acyclovir 10mg",
  "ACYCLOVIR DISPERSIBLETABLETSIP 800 MG 5's",
  "Acyclovir ER",
  "Acyclovir EyeOintment 5 gm",
  "Acyclovir SR",
  "Adalimumab",
  "Adalimumab 10mg",
  "Adalimumab ER",
  "Adalimumab SR",
  "Adapalene",
  "Adapalene 0.1 % w/ vOintment 15 gtubes",
  "Adapalene 10mg",
  "Adapalene ER",
  "Adapalene SR",
  "Adenosine Injection 3 mg/ ml 2 ml",
  "Adrenaline",
  "Adrenaline 10mg",
  "Adrenaline ER",
  "Adrenaline SR",
  "Albendazole",
  "Albendazole 10mg",
  "ALBENDAZOLE 400 mg + IVERMECTIN 6 mg Tablets 1's",
  "Albendazole 400 mgTabs IP 10's",
  "Albendazole ER",
  "Albendazole SR",
  "Albendazole(200 mg/ 5 ml) SyrupIP 10 ml",
  "ALFACALCIDOL SOFT GELATIN CAPSULES 0.25 MCG",
  "Allopurinol",
  "Allopurinol 100 mgTabs IP 10's",
  "Allopurinol 10mg",
  "Allopurinol ER",
  "Allopurinol SR",
  "Alprazolam",
  "Alprazolam 0.25 mg film coated Tablets IP 10's",
  "Alprazolam 0.5  mg film coated Tablets IP 10's",
  "Alprazolam 10mg",
  "Alprazolam ER",
  "Alprazolam SR",
  "Alprazolam-0.25 mg, Fluoxetine 20 mg Tablets 10's",
  "Aluminium Hydroxide + Magnesium Hydroxide(250+250 mg/ 5 ml) Suspension",
  "Amantadine",
  "Amantadine 10mg",
  "Amantadine ER",
  "Amantadine SR",
  "Amikacin",
  "Amikacin 10mg",
  "Amikacin 250 mg/ ml inj . IP 2 ml Vial",
  "Amikacin 250 mginj . IP 2 ml Vial",
  "Amikacin ER",
  "Amikacin SR",
  "Amikacin Sulphate 50 mg/ ml inj . IP 2 ml Vial",
  "Aminocaproic Acid",
  "Aminocaproic Acid ER",
  "Aminocaproic Acid SR",
  "AMIODARONE Tablets IP 200 mg 10's",
  "Amisulpride Tablets I.P 50 mg 10's",
  "Amitriptyline hydrochloride 10 mg TabletsI.P 10's",
  "Amlodipine",
  "Amlodipine + Atenolol(5 mg + 50 mg) filmcoated Tablets",
  "Amlodipine 10mg",
  "AMLODIPINE 5 MG + LISINOPRIL 5 MGTABLETS 15's",
  "Amlodipine 5 mg Tablets IP 10's",
  "Amlodipine ER",
  "Amlodipine SR",
  "Amoxicillin",
  "Amoxicillin 10mg",
  "Amoxicillin ER",
  "Amoxicillin SR",
  "Amoxycillin + Clavulanicacid(1000 mg + 200 mg) Powder for InjectionIP",
  "Amoxycillin + Clavulanicacid(200 mg+28.5 mg/ 5 ml) Powder for suspensionIP",
  "Amoxycillin + Clavulanicacid(250 mg + 50 mg) Powderfor injectionIP",
  "Amoxycillin + Clavulanicacid(500 mg + 125 mg) filmcoated Tablets IP",
  "Amoxycillin 125 mg / 5 ml Powder for Suspension IP 60 ml",
  "Amoxycillin 125 mg KidTabs IP 10's",
  "AMOXYCILLIN 250 mg + CLOXACILLIN 250 mgCapsules",
  "Amoxycillin 250 mg Caps IP 10's",
  "AMOXYCILLIN 250 mg WITH POTASSIUM CLAVULANATE 125 mg Tablets IP",
  "Amoxycillin 500 mg Caps IP 10's",
  "AMOXYCILLIN and POTASSIUM CLAVULANATE Tablets IP(875 mg+125 mg) 500+125",
  "Amphotericin B",
  "Amphotericin B ER",
  "Amphotericin B SR",
  "Ampicillin Injections I.P. 500 mg Vial &",
  "Anastrozole Tablets IP 1 mg 10's",
  "ANTACID Tablets [ DRIEDAl(OH) 3 + Mg(OH) 2 + SIMETHICONE(250 mg + 250 mg + 50 mg)",
  "APPETITE ENHANCER (PEPTONE, MINERALS, VITAMINS)SYRUP",
  "Aprepitant",
  "Aprepitant 10mg",
  "Aprepitant ER",
  "Aprepitant SR",
  "Arteether 150 mg/ 2 ml inj IP 2 ml Vial",
  "ARTEMETHER 80 MG + LUMEFANTRINE(BANFLUMETOL) 480 MG SR TABLETS",
  "ARTESUNATE INJECTION 60 MG 1 Vial",
  "Ascorbic Acid Tablets IP 100 mg(Vitamin-C Chewable Tablet IP 100 mg)",
  "Aspirin",
  "Aspirin 10mg",
  "ASPIRIN 75 mg + CLOPIDOGREL 75 mg Tablets 10's",
  "Aspirin ER",
  "Aspirin SR",
  "ASPIRIN Tablets IP 150 mg 14's",
  "Aspirin enteric coated Tablets I.P. 75 mg 14's",
  "Atazanavir",
  "Atazanavir 10mg",
  "Atazanavir ER",
  "Atazanavir SR",
  "Atenolol",
  "Atenolol 10mg",
  "Atenolol 25 mg, Amlodipine 5 mg Tablets 14's",
  "Atenolol 25 mgtab 14's",
  "Atenolol 50 mgTabs IP 14's",
  "Atenolol ER",
  "Atenolol SR",
  "Atorvastatin",
  "Atorvastatin + Clopidogrel (10/ 75 mg) Capsules 10's",
  "ATORVASTATIN 10 mg + FENOFIBRATES 160 mg Tablets",
  "Atorvastatin 10 mg film coated Tablets IP 10's",
  "Atorvastatin 10 mg",
  "Atorvastatin 20 mg film coated Tablets IP 10's",
  "Atorvastatin ER",
  "Atorvastatin SR",
  "ATORVASTATIN Tablets IP 40 mg 10's",
  "Atorvastatin I.P 10 mg, Aspirin I.P(EC) 75 mg Capsules 10's",
  "Atracurium Besilate Injection I.P 25 mg/ 2.5 ml 2.5 ML",
  "Atropine",
  "Atropine 10mg",
  "Atropine ER",
  "Atropine SR",
  "ATROPINE SULPHATE INJECTIONIP 0.6 MG / ML 1 ML",
  "Azathioprine",
  "Azathioprine 10mg",
  "Azathioprine ER",
  "Azathioprine SR",
  "Azithromycin",
  "Azithromycin 10mg",
  "Azithromycin 250  mg film coated Tablets IP 10's",
  "Azithromycin 500  mg film coated Tablets IP 10's",
  "Azithromycin ER",
  "Azithromycin SR",
  "Azithromycin(100 mg/ 5 ml) Suspension IP 15 ml",
  "b --Sanitary Napkin, Belt-type 1 . Covering Covering of the absorbent filler shall be good quality knitted sleeve or non-",
  "Bacitracin",
  "Bacitracin 10mg",
  "Bacitracin ER",
  "Bacitracin SR",
  "Bacitracin Zinc 250 Iu Neomycin 5 Mg, Sulphacetamide Sodium 60 Mg Per 1 gm Powder",
  "Baclofen",
  "Baclofen 10mg",
  "Baclofen ER",
  "Baclofen SR",
  "BACLOFEN Tablets IP 10 mg 10's",
  "Beclamethasone Dipropionate..0.025 % w/, Neomycin Sxulphate..0.5 % w/w (3500 Unit/ G) Chlorocresol 0.1 %",
  "Beclomethasone",
  "Beclomethasone ER",
  "Beclomethasone SR",
  "BECLOMETHASONEIP 0.025 % w/w+ CLOTRIMAZOLE IP 1 % w/w+ GENTAMYCIN IP",
  "Benzoyl Peroxide",
  "Benzoyl Peroxide 10mg",
  "Benzoyl Peroxide ER",
  "Benzoyl Peroxide SR",
  "Betahistine TabletsI.P. strength 8 mg 10 s",
  "Betamethasone",
  "Betamethasone 0.05 % w/ w + Salicylicacid 3 % w/ w 20 Gm",
  "Betamethasone 10mg",
  "Betamethasone ER",
  "Betamethasone Injection",
  "Betamethasone Injection 10mg",
  "Betamethasone Injection ER",
  "Betamethasone Injection SR",
  "Betamethasone SR",
  "BetamethasoneInj . I.P 4 mg/ ml 1 ml",
  "BETAMETHASONETABLETSIP 0.5 MG 20's",
  "BETAMETHASONEVALERAT 0.1 % w/ w + NEOMYCIN SULFATE 0.5 % w/w CREAM",
  "BicalutamideTabI.P 50 mg 10's",
  "BiphasicIsophaneInsulinInjectionI.P 100 Iu/ ml(30: 70)(30 % SolubleInsulinAnd 70 % IsophaneInsulin)",
  "BiphasicIsophaneInsulinInjectionIP 4 OIU/ ML(50: 50) 10 ml Vial",
  "Bisacodyl",
  "Bisacodyl 10mg",
  "Bisacodyl 5 mg Tablets IP 10's",
  "Bisacodyl ER",
  "Bisacodyl SR",
  "BISOPROLOLTABLETS 5 MG 10's",
  "Blood administrationset/ Blood transfusionsetOne",
  "BoneWax, SterilisedOne",
  "BortezomibInjection 3.5 mgVial",
  "Bosentan",
  "Bosentan ER",
  "Bosentan SR",
  "Brimonidine",
  "Brimonidine 10mg",
  "Brimonidine ER",
  "Brimonidine SR",
  "BromfenacSodiumEyeDrop 0.09 % 5 ml",
  "Budecort",
  "Budecort ER",
  "Budecort SR",
  "Budesonide",
  "Budesonide 10mg",
  "Budesonide ER",
  "Budesonide SR",
  "BUDESONIDERESPULES 0.5 MG 2 ML",
  "Bupropion",
  "Bupropion 10mg",
  "Bupropion ER",
  "Bupropion SR",
  "Calaminelotion 100 ml 100 ml",
  "Calcitriol Capsules I.P 0.25 mcg 10's",
  "CALCIUM 500 mg+ CALCITRIOL 0.25 mg Tablets 15's",
  "Calcium Carbonate",
  "Calcium Carbonate 10mg",
  "Calcium Carbonate ER",
  "Calcium Carbonate SR",
  "Calcium Citrate",
  "Calcium Citrate 10mg",
  "Calcium Citrate ER",
  "Calcium Citrate SR",
  "Calciumcarbonate 1250 mg + VitaminD3 250 iu Tabletsfilmcoated",
  "CALCIUM€CARBONATE 500 MG + CALCITRIOL 0.25 MCG + ZINC 7.5 MG Tablets",
  "Canagliflozin",
  "Canagliflozin 10mg",
  "Canagliflozin ER",
  "Canagliflozin SR",
  "CapecitabineTabI.P 500 mg 10's",
  "Carbamazepine",
  "Carbamazepine 100 mgTabs IP 10's",
  "Carbamazepine 10mg",
  "Carbamazepine 200 mgTabs IP 10's",
  "Carbamazepine ER",
  "Carbamazepine SR",
  "CARBIMAZOLETABLETSIP 5 MG 10's",
  "Carboprost TromethamineInjectionIP 250 mcg/ ml 1 ml",
  "CARBOXYMETHYLCELLULOSEEYEDROPSIP 0.5 % w/ v",
  "Carvedilol Tablets IP 6.25 mg 10's",
  "CARVEDILOLTABLETSIP 3.125 MG 10's",
  "Caspofungin",
  "Caspofungin ER",
  "Caspofungin SR",
  "Cefadroxil filmcoated Tablets IP 250 mg 10's",
  "Cefixime",
  "Cefixime 100  mg film coated Tablets IP 10's",
  "Cefixime 10mg",
  "CEFIXIME 200 mg + CLAVULANICACID 125 mg(ASPOT .CLAVULANATE) Tablets",
  "CEFIXIME 200 mg + OFLOXACIN 200 mg Tablets 10's",
  "Cefixime 200  mg film coated Tablets IP 10's",
  "Cefixime ER",
  "Cefixime SR",
  "CefiximeOral SuspensionIP 50 mg/ 5 ml 30 ml",
  "Cefoperazone + Sulbactam(1 g + 1 g) Inj . IPVial & wfi",
  "Cefoperazone + Sulbactam(500 mg + 500 mg) Inj . Vial & wfi",
  "Cefoperazone 1 gmInj . IPVial",
  "CEFOTAXIMESODIUM 250 MG & SULBACTAMSODIUM 125 MGINJECTION",
  "CefotaximeSodiumInjectionsIP 1000 mgVial &",
  "CefotaximeSodiumInjectionsIP 250 mgVial &",
  "Cefpodoxime 100 mg IP 10's",
  "CEFPODOXIME 200 mg+ CLAVULANICACID 125 mg Tablets",
  "Cefpodoxime 200  mg film coated Tablets IP 10's",
  "Cefpodoximeproxetil 50 mgDSdrysyrup 30 ml",
  "CefpodoximeProxetil dispersibletablet 50 mg 10's",
  "Ceftazadime 1000 mgInjectionsVial &",
  "Ceftazadime 500 mgInjectionsVial &",
  "Ceftriaxone",
  "Ceftriaxone + Sulbactam(1000 mg + 500 mg) Inj . Vial & wfi",
  "Ceftriaxone + Tazobactum 1000 mg + 125 mgInj . Vial & wfi",
  "Ceftriaxone +Sulbactam(250 mg + 125 mg) Vial & wfi",
  "Ceftriaxone +Sulbactam(500 mg + 250 mg) Injections 10 ml Vial",
  "Ceftriaxone 10mg",
  "Ceftriaxone 250 mgInj . IPVial & wfi",
  "Ceftriaxone ER",
  "Ceftriaxone InjectionsIP 1 g 5 ml Vial",
  "Ceftriaxone SR",
  "Cefuroxi meAxetil 500  mg film coated Tablets IP 10's",
  "Cefuroxime",
  "Cefuroxime 10mg",
  "Cefuroxime 125 mgtablet 6's",
  "CEFUROXIME 500 mg+ CLAVULANICACID 125 mg(AS POT .CLAVULANATE) Tablets",
  "Cefuroxime ER",
  "Cefuroxime SR",
  "CefuroximeAxetil 250  mg film coated Tablets IP 10's",
  "CefuroximeInjection 1500 mg 10 ml",
  "Cephalexin 125 mg/ 5 ml drysyrup 30 ml",
  "Cephalexin 125 mgDT IP 10's",
  "Cephalexin 250 mgCaps IP 10's",
  "Cephalexin 500 mgCaps IP 10's",
  "Cetirizine",
  "Cetirizine 10mg",
  "Cetirizine ER",
  "Cetirizine SR",
  "Cetrizine 10  mg film coated Tablets IP 10's",
  "Cetrizine(5 mg/ 5 ml) Syrup IP 60 ml",
  "ChlorhexidineGluconate 0.3 % v/ v + Cetrimide 0.6 % w/ v 100 ml",
  "ChlorhexidineGluconate 0.3 % v/ v + Cetrimide 0.6 % w/ v 200 ml",
  "CHLORHEXIDINEMOUTHWASHIP 0.2 % w/v 100 ml",
  "ChloroquinePhosphate 250  mg film coated Tablets 10's",
  "Chlorthalidone Tablets 12.5 mg 10's",
  "Cholecalciferol",
  "Cholecalciferol -60000 iugranules 1 gm",
  "Cholecalciferol 10mg",
  "Cholecalciferol ER",
  "Cholecalciferol SR",
  "Chromic(1/2 Cir RB Needle 4 5 mm, Length 1 0 0 cm) One",
  "Chromic(3/8 Cir RB Needle 4 0 mm, Length 7 6 cm) One",
  "Chromic(3/8 Cir RCuttingNeedle 2 6 mm, Length 7 6 cm) One",
  "Chromic(3/8 RB Needle 3 0 mm, Length 7 6 cm) One",
  "Chromic(l/2 Cir RB Needle 2 0 mm, Length 7 6 cm) One",
  "Chromic(l/2 Cir RB Needle 3 0 mm, Length 7 6 cm) One",
  "Chromic(l/2 Cir RB Needle 4 0 mm, Length 7 6 cm) One",
  "CHYMOTRYPSIN + TRYPSIN(1: 6) TABLETS 100 KAU",
  "Ciclesonide",
  "Ciclesonide ER",
  "Ciclesonide SR",
  "Ciclosporin",
  "Ciclosporin 10mg",
  "Ciclosporin ER",
  "Ciclosporin SR",
  "Cilnidipine Tablets 20 mg 10's",
  "Cilostazol Tablets IP 50 mg 10's",
  "Cinnarizine Tablets 25 mg 10's",
  "Ciprofloxacin",
  "Ciprofloxacin + Tinidazole(500 mg + 600 mg) filmcoated Tablets",
  "Ciprofloxacin 0.3 % w/ V Eyedrops 5 ml",
  "Ciprofloxacin 10mg",
  "CIPROFLOXACIN 250 MG+ TINIDAZOLE 300  mg film coatedTABLETS",
  "Ciprofloxacin 250  mg film coated Tablets IP 10's",
  "Ciprofloxacin 500  mg film coated Tablets IP 10's",
  "Ciprofloxacin ER",
  "Ciprofloxacin SR",
  "CIPROFLOXACININJECTIONIP 2 MG/ ML 100 ml",
  "CISPLATININJECTIONIP 10 MGVIAL &",
  "Citalopram",
  "Citalopram 10mg",
  "Citalopram ER",
  "Citalopram SR",
  "Citicoline Tablets 500 mg 10's",
  "Clarithromycin",
  "Clarithromycin 10mg",
  "Clarithromycin 250 mgtablet 10's",
  "Clarithromycin ER",
  "Clarithromycin SR",
  "CLARITHROMYCIN Tablets IP 500 mg 4's",
  "CLIDINIUMBROMIDE 2.5 MG+ CHLORDIAZEPOXIDE 5  mg film coated",
  "CLINDAMYCINCAPSULESIP 300 MG 10's",
  "CLINDAMYCININJ IP 300 MG/ 2 ML 2 ML",
  "Clobazam Tablet 5 mg 10's",
  "Clobetasol",
  "Clobetasol 10mg",
  "Clobetasol ER",
  "Clobetasol SR",
  "Clomiphene citrate TabletsI.P. strength 50 mg 10 s",
  "Clonazepam",
  "Clonazepam 0.5 mgTabs IP",
  "Clonazepam 10mg",
  "Clonazepam ER",
  "Clonazepam SR",
  "Clonazepam Tablets IP 1 mg 10's",
  "Clopidogrel",
  "Clopidogrel 10mg",
  "Clopidogrel 75 mgTabs IP 10's",
  "Clopidogrel Bisulfate",
  "Clopidogrel Bisulfate 10mg",
  "Clopidogrel Bisulfate ER",
  "Clopidogrel Bisulfate SR",
  "Clopidogrel ER",
  "Clopidogrel SR",
  "Clotrimazole",
  "Clotrimazole 1 % 100 gmpowder 100 gm",
  "Clotrimazole 1 % w/ w 0 int . IP 15 gtubes",
  "Clotrimazole 1 % w/ w, BeclometasoneDipropionate",
  "Clotrimazole 100 mgVaginal Tab 10's",
  "Clotrimazole 10mg",
  "Clotrimazole ER",
  "Clotrimazole SR",
  "Co-Trimoxazole",
  "Co-Trimoxazole 10mg",
  "Co-Trimoxazole ER",
  "Co-Trimoxazole SR",
  "Coenzyme Q10",
  "Coenzyme Q10 10mg",
  "Coenzyme Q10 ER",
  "Coenzyme Q10 SR",
  "ColdSuspn.N/ F(Paracetamol 125 mg+ PhenylephrineHydroclorideIP 5 mg +",
  "Corrugated DrainageSheet, Sterile, Multichannel, withradioopaqueline, SingleUse - Allsizes",
  "COTEDPOLYSTERBRAIDED { GREEN/ BLUE } SIZE 3/0 1/2 cir Tapercut, 2 5 mmdoubleneedlelength 9 0 cm",
  "CottonBandages(NonSterile), Size 1 0 cmX4 Masper ScheduleF-II",
  "CottonBandages(NonSterile), Size 7 . 5 cmX4 MasperScheduleF-II",
  "COUGHSYRUP [DIPHEN.14 mg. + AMMONIUMCHL.135 mg. + SOD.CIT .57 mg. + MENTHOL 0.9",
  "CrepeBandageB . P . 1 0 cmX4 meter 1 's",
  "CrepeBandageB . P . 1 5 cmX4 meter 1 's",
  "Cyclobenzaprine",
  "Cyclobenzaprine 10mg",
  "Cyclobenzaprine ER",
  "Cyclobenzaprine SR",
  "Cyproheptadine 4 mg 10's",
  "CYPROHEPTADINE Tablets IP 4 mg 10's",
  "Cyproheptadine, Hydrochloride(anhydrous) IP..2 mg.Ina",
  "Daclatasvir",
  "Daclatasvir 10mg",
  "Daclatasvir ER",
  "Daclatasvir SR",
  "Dandruf Shampoo KETOCONAZOLEIPSHAMPOO 2 % W/ V",
  "Dapagliflozin",
  "Dapagliflozin 10mg",
  "Dapagliflozin ER",
  "Dapagliflozin SR",
  "Darunavir",
  "Darunavir 10mg",
  "Darunavir ER",
  "Darunavir SR",
  "DEFLAZACORT Tablets 6 mg 6's",
  "Dehydroepiandrosterone 25 mgCapsule 10's",
  "Dexamethasone",
  "DEXAMETHASONE 0.5 MGTABS IP 10's",
  "Dexamethasone 10mg",
  "Dexamethasone ER",
  "Dexamethasone SR",
  "Dexamethasone TabletsI.P. strength 0.5 mg 10 s",
  "DEXAMETHASONEINJECTIONIP 4 MG/ ML 2 ML",
  "DextromethorphanHBr SyrupIP 13.5 mg/ 5 ml 50 ml",
  "Diacerein 50 mg + GlucosamineSulphate 500 mg 10's",
  "Diacerein 50 mg +Methylsulphonylmethane 250 mg + Glucosaminesulphate 750 mgtab.",
  "DiacereinCapsules IP 50 mg 10's",
  "Diazepam",
  "Diazepam 10mg",
  "Diazepam 5 mgTabs IP 10's",
  "Diazepam ER",
  "Diazepam SR",
  "Diclofenac + Menthol 5 % + Oleum 3 % + MethylSalicylateGel",
  "DICLOFENAC 1.16 w/ w+ LINCEEDOIL3 % w/w+ METHYLSALICYLATE 10 % w/w+MENTHOL 5 %",
  "DICLOFENAC 50 mg+ PARACETAMOL 325 mg+ CHLORZOXAZONE 500 mg Tablets",
  "DiclofenacdiethylamineBP 1.116 %(equivalent todiclofenacsodium 1.0 %, Linseedoil BP 3.0 % + Methyl",
  "DiclofenacGel(DiclofenecDiethylamine 1.16 % w/ w) BP",
  "DiclofenacPotassiumBP 50 mg + Paracetamol 325 mg + Serratiopeptidase 10 mg",
  "DiclofenacSodium + Serratiopeptidase(50 mg + 10 mg) Tab",
  "DiclofenacSodium 25 mgper ml Inj . IP 3 ml",
  "DiclofenacSodium 50 mgTab IP 10's",
  "DiclofenacSodium(SR) Tablets IP 100 mg 10's",
  "Dicyclomine",
  "Dicyclomine 10 mg + Act . Dimethicone 40 mgper ml 10 ml",
  "DICYCLOMINE 10 MG + DIMETHICONE 40 MG/ 5 MLSUSPENSION",
  "Dicyclomine 10 mg + Mefenamic 250 mg 10's",
  "DICYCLOMINE 10 mg+ MEFENAMICACID 250 mg Tablets",
  "Dicyclomine 10 mgTabs IP 10's",
  "Dicyclomine 10mg",
  "Dicyclomine ER",
  "Dicyclomine SR",
  "DicyclomineHCL + Paracetamol(20 mg + 325 mg) Tablets",
  "DicyclomineHCl(Dicycloverine) InjectionIP 10 mg/ ml 2 ml",
  "DIETHYLCARBAMAZINE Tablets IP 50 mg 30's",
  "DIGOXIN Tablets IP 250 µg [ 0.25 mg ] 10's",
  "Diltiazem",
  "Diltiazem 10mg",
  "Diltiazem ER",
  "Diltiazem SR",
  "Diltiazem TabletsI.P. strength 30 mg 10 s",
  "DILTIAZEMTABLETS SR 90 MG 10's",
  "DisodiumhydrogenCitrate(Alkalyser) 1.4 mg/ 5 ml Syrup 100 ml",
  "DISPOSABLE STERILE SURGICALRUBBERGLOVESSIZE 8 INCHES, Conformsto IS 1 3 4 2 2, ISImarked/ CE",
  "DisposableSterileSurgicalRubber Gloves, Size 6 Inches, Conformsto IS 1 3 4 2 2, ISImarked/ CEcertified/ FDAapproved",
  "Disposalsterilesurgicalrubber glovessize 7 1/2 inches, Conformsto IS 1 3 4 2 2, ISImarked/ CEcertified/ FDA",
  "Disposalsterilesurgicalrubber glovessize 7 inches, Conformsto IS 1 3 4 2 2, ISImarked/ CEcertified/ FDAapproved",
  "DisulfiramIP 500 mg 4 s",
  "Dobutamine 250 mg/ 20 ml Inj . IPVial",
  "Docusate Sodium",
  "Docusate Sodium 10mg",
  "Docusate Sodium ER",
  "Docusate Sodium SR",
  "Dolutegravir",
  "Dolutegravir 10mg",
  "Dolutegravir ER",
  "Dolutegravir SR",
  "Domperidone",
  "Domperidone + Esomeprazole(30/ 40 mg) Capsule 10's",
  "Domperidone 10mg",
  "DOMPERIDONE 30 mg+ PANTOPRAZOLE 40 mgCapsules [ SR]",
  "Domperidone 5 mg./ 5 ml Syrup IP 30 ml",
  "Domperidone ER",
  "Domperidone SR",
  "Domperidone Tablets IP 10 mg 10's",
  "Donepezil",
  "Donepezil 10mg",
  "Donepezil ER",
  "Donepezil SR",
  "DOXOFYLLINETABLETSIP 400 MG 10's",
  "Doxorubicin 10 mgInj . IPVial",
  "Doxorubicin 50 mgInj . IPVial",
  "Doxycycline",
  "Doxycycline 10mg",
  "Doxycycline ER",
  "Doxycycline SR",
  "DOXYLAMINESUCCINATE 10 mg+ PYRIDOXINEHCl 10 mg Tablets",
  "DrotaverineHCl 80 mg, MefenamicAcid 250 mg Tablets 10's",
  "DrotaverineHCl Tablets IP 40 mg 10's",
  "Duloxetine",
  "Duloxetine 10mg",
  "Duloxetine ER",
  "Duloxetine SR",
  "DustingPowder(Povidone 5 % Powder 10 Gm",
  "Ear Drops(Paradichlorobenzene 2 % +Benzocaine 2.7 % +Chlorbutol 5 % +TurpentineOil 15 %",
  "EbastineFilmCoated Tablets 10 mg 10's",
  "Efavirenz",
  "Efavirenz 10mg",
  "Efavirenz ER",
  "Efavirenz SR",
  "Efavirenz Tablets IP 600 mg 30's",
  "Empagliflozin",
  "Empagliflozin 10mg",
  "Empagliflozin ER",
  "Empagliflozin SR",
  "Emtricitabine",
  "Emtricitabine 10mg",
  "Emtricitabine ER",
  "Emtricitabine SR",
  "Enalapril",
  "Enalapril 10mg",
  "Enalapril ER",
  "Enalapril SR",
  "Enalpril TabletsI.P. strength 5 mg 10 s",
  "ENDOTRACHEALTUBE, CUFFED, SIZE 4 . 5,, Softcufftowardsthedistalend, Kinkresistantinflationtube, Sterile,",
  "ENDOTRACHEALTUBE, CUFFED, SIZE 4, Softcufftowardsthedistalend, Kinkresistantinflationtube, Sterile,",
  "ENDOTRACHEALTUBE, CUFFED, SIZE 5, Softcufftowardsthedistalend, Kinkresistantinflationtube, Sterile,",
  "ENDOTRACHEALTUBE, CUFFED, SIZE 6 . 5, Softcufftowardsthedistalend, Kinkresistantinflationtube, Sterile,",
  "ENDOTRACHEALTUBE, CUFFED, SIZE 6, Softcufftowardsthedistalend, Kinkresistantinflationtube, Sterile,",
  "ENDOTRACHEALTUBE, CUFFED, SIZE 7 . 5, Softcufftowardsthedistalend, Kinkresistantinflationtube, Sterile,",
  "ENDOTRACHEALTUBE, CUFFED, SIZE 7, Softcufftowardsthedistalend, Kinkresistantinflationtube, Sterile,",
  "ENDOTRACHEALTUBE, CUFFED, SIZE 8 . 5 Softcufftowardsthedistalend, Kinkresistantinflationtube, Sterile,",
  "ENDOTRACHEALTUBE, CUFFED, SIZE 8, Softcufftowardsthedistalend, Kinkresistantinflationtube, Sterile,",
  "ENDOTRACHEALTUBE, CUFFED, SIZE 9 Softcufftowardsthedistalend, Kinkresistantinflationtube, Sterile,",
  "ENDOTRACHEALTUBE, PLAIN, SIZE 2 . 5, Singleuse, sterile, Standard 1 5 mmconnector atproximalend, Tip suitable",
  "ENDOTRACHEALTUBE, PLAIN, SIZE 3, Singleuse, sterile, Standard 1 5 mmconnector atproximalend, Tip suitablefor",
  "ENDOTRACHEALTUBE, PLAIN, SIZE 4 . 5 Singleuse, sterile, Standard 1 5 mmconnector atproximalend, Tip suitablefor",
  "ENDOTRACHEALTUBE, PLAIN, SIZE 4, Singleuse, sterile, Standard 1 5 mmconnector atproximalend, Tip suitablefor",
  "ENDOTRACHEALTUBE, PLAIN, SIZE 5, to 8,, Singleuse, sterile, Standard 1 5 mmconnector atproximalend, Tip suitable",
  "ENDOTRACHEALTUBE, PLAIN, SIZE 8 . 5, Singleuse, sterile, Standard 1 5 mmconnector atproximalend, Tip suitable",
  "ENDOTRACHEALTUBE, PLAIN, SIZE, 3 . 5, Singleuse, sterile, Standard 1 5 mmconnector atproximalend, Tip suitable",
  "Enoxaparin 40 mg/ 0.4 ml Inj . IP 0.4 ml",
  "Enoxaparin 60 mg/ 0.6 ml Inj . IP 0.6 ml",
  "Entacapone",
  "Entacapone 10mg",
  "Entacapone ER",
  "Entacapone SR",
  "EnymeSyrupMixFruit Flavour Pepsin 7.5 mg + FungalDiastase 12.5 mg/ 5 ml",
  "EnzymeDrops Pepsin(1: 3000) 5 mg + Fungal Diastase(1: 1200) 33.33 mg/ ml",
  "Epinephrine",
  "Epinephrine 10mg",
  "Epinephrine ER",
  "Epinephrine SR",
  "Erythromycin",
  "Erythromycin 10mg",
  "Erythromycin ER",
  "Erythromycin SR",
  "Escitalopram",
  "Escitalopram 10 mgTabs IP",
  "Escitalopram 10 mgwith Clonazepam 0.5 mg 10's",
  "Escitalopram 10mg",
  "Escitalopram 20 mgTabs IP",
  "Escitalopram ER",
  "Escitalopram Oxalate",
  "Escitalopram Oxalate 10mg",
  "Escitalopram Oxalate ER",
  "Escitalopram Oxalate SR",
  "Escitalopram SR",
  "Esomeprazole",
  "Esomeprazole 10mg",
  "Esomeprazole ER",
  "Esomeprazole SR",
  "ESOMEPRAZOLE Tablets IP 40 mg(ENTERICCOATED)",
  "Etanercept",
  "Etanercept 10mg",
  "Etanercept ER",
  "Etanercept SR",
  "ETHAMBUTOL TABLETSIP 800 MG 10's",
  "Ethinylestradiol",
  "Ethinylestradiol 10mg",
  "Ethinylestradiol ER",
  "Ethinylestradiol SR",
  "Etizolam Tablet 0.5 mg 10's",
  "Etophyllin +Theophylline(77 mg + 23 mg) Tabs 10's",
  "EtophyllineIP 115 mg + Theophylline 35 mg Tablet 10's",
  "Etoricoxilb 120 mgTab IP 10's",
  "Etoricoxilb 90 mgTab IP 10's",
  "FACE MASK, DISPOSABLE, Should bemanufactured fromnonwovenpolyprop fabric, Should be 3 plyconstruction",
  "Famotidine",
  "Famotidine 10mg",
  "Famotidine ER",
  "Famotidine SR",
  "FAMOTIDINETABLETSIP 20 MG 14's",
  "FAMOTIDINETABLETSIP 40 MG 14's",
  "Febuxostat Tablets 40 mg 10's",
  "Febuxostat Tablets 80 mg 10's",
  "Ferric Carboxymaltose",
  "Ferric Carboxymaltose 10mg",
  "Ferric Carboxymaltose ER",
  "Ferric Carboxymaltose SR",
  "Ferrous Sulfate",
  "Ferrous Sulfate 10mg",
  "Ferrous Sulfate ER",
  "Ferrous Sulfate SR",
  "FERROUSAMMONIUMCITRATE 160 MG + CYANOCOBALAMINE 7.5 MCG + FOLICACID 0.5 MG/15 ML",
  "FERROUSASCORBATE 100 MGWITH FOLICACID 1.5 MGTABLETS",
  "Fexofenadine 120  mg film coated Tablets IP",
  "Fexofenadine 180  mg film coated Tablets IP",
  "Filgrastim 300 mcg/ 1 ml PrefilledSyringe 1's",
  "Finaestride 5 mg 10's",
  "Finasteride",
  "Finasteride 10mg",
  "Finasteride ER",
  "Finasteride SR",
  "Fluconazole",
  "Fluconazole 10mg",
  "Fluconazole 150 mg Tablets IP 10's",
  "Fluconazole ER",
  "Fluconazole SR",
  "Flucytosine",
  "Flucytosine ER",
  "Flucytosine SR",
  "FLUNARZINETABLETS 10 MG 10's",
  "FLUNARZINETABLETS 5 MG 10's",
  "Flunisolide",
  "Flunisolide ER",
  "Flunisolide SR",
  "Fluoxetine",
  "Fluoxetine 10mg",
  "Fluoxetine ER",
  "Fluoxetine SR",
  "Fluoxetinehydrochloride 20 mgCaps IP 10's",
  "Fluticasone",
  "Fluticasone 10mg",
  "Fluticasone ER",
  "Fluticasone SR",
  "FLUTICASONEPROPIONATE 50 MCGPERPUFFNASALSPRAY",
  "FLUTICASONEPROPIONATERESPULE 0.5 MG/2 ML 2 ML",
  "Folic Acid",
  "Folic Acid 10mg",
  "Folic Acid ER",
  "Folic Acid SR",
  "FolicAcid Tablets IP 5 mg 10's",
  "Frusemide 40 mgTabs IP 10's",
  "FRUSEMIDEINJECTIONIP(10 MG/ ML) 2 ML",
  "Furosemide",
  "Furosemide 10mg",
  "Furosemide ER",
  "Furosemide SR",
  "FusidicAcidCreamI.P. strength 2 % w/ v 10 gtubes",
  "Gabapentin",
  "Gabapentin 10mg",
  "Gabapentin ER",
  "Gabapentin SR",
  "Gabapentin+Nortriptyline(400/ 10 mg) Tablets 10's",
  "GabapentinCapsules USP 300 mg 10's",
  "Galantamine",
  "Galantamine 10mg",
  "Galantamine ER",
  "Galantamine SR",
  "Gemcitabine 1000 mgInj . IPVial",
  "Gemcitabine 200 mgInj . IPVial",
  "Gentamicin",
  "Gentamicin 10mg",
  "Gentamicin ER",
  "Gentamicin SR",
  "Glibenclamide",
  "Glibenclamide 10mg",
  "Glibenclamide 2.5 mgTabs IP 10's",
  "Glibenclamide 5 mg + MetforminHcl 500 mgtab 10's",
  "Glibenclamide 5 mgTabs IP 10's",
  "Glibenclamide ER",
  "Glibenclamide SR",
  "Gliclazide 40 mgTabs IP",
  "GLICLAZIDE 80 mg + METFORMINHYDROCHLORIDE Tablets 5 0 0 mg",
  "Gliclazide 80 mgTabs IP",
  "GLICLAZIDETABS/CAPSSR 60 MG 10's",
  "Glimeperide 1 mgTab IP 10's",
  "Glimeperide 2 mgTabs IP 10's",
  "Glimepiride",
  "Glimepiride 1 mgMetformin 500 mg Tablets 10's",
  "Glimepiride 10mg",
  "GLIMEPIRIDE 2 mg + METFORMINHYDROCHLORIDE 5 0 0 mgSR Tablets",
  "Glimepiride 2 mg, MetforminHydrochloride 1 g Tablets 10's",
  "Glimepiride ER",
  "Glimepiride SR",
  "Glimipride 3 mgtablet 10's",
  "Glimipride 4 mgtablet 10's",
  "GLIPIZIDE 5 MG + METFORMINHYDROCHLORIDE 500 MGTABLETS",
  "Glipizide 5 mg Tablets IP 10's",
  "Glycerinip 98 % w/ w 50 gm",
  "GUAIFENESIN 100 mg+ TERBUTALINE 2.5 mg+ BROMHEXINE 8 mg/ 10 ml SYRUP",
  "Haematinic Syrupof Iron, acidandVitaminB12 100 ml 100 ml",
  "Haloperidol",
  "Haloperidol 10mg",
  "Haloperidol ER",
  "Haloperidol SR",
  "Hydrochlorothiazide",
  "Hydrochlorothiazide 10mg",
  "Hydrochlorothiazide ER",
  "Hydrochlorothiazide SR",
  "Hydrocodone",
  "Hydrocodone 10mg",
  "Hydrocodone ER",
  "Hydrocodone SR",
  "Hydrocortisone Cream",
  "Hydrocortisone Cream 10mg",
  "Hydrocortisone Cream ER",
  "Hydrocortisone Cream SR",
  "Hydrocortisone Injection",
  "Hydrocortisone Injection 10mg",
  "Hydrocortisone Injection ER",
  "Hydrocortisone Injection SR",
  "Hydrocortisone SodiumSuccinateInjectionIP 100 mgVial",
  "HYDROQUINONE 2 % + MOMETASONE 0 . 1 % + TRETINOIN 0.025 % cream",
  "Hydroquinone 2.0 % w/ w + Tretinoin 0.025 % w/ w + MometasoneFuroate 0.1 % w/ winacreambaseq.s",
  "Hydroxychloroquine",
  "Hydroxychloroquine 10mg",
  "Hydroxychloroquine ER",
  "Hydroxychloroquine SR",
  "HYDROXYCHLOROQUINE Tablets IP 200 mg 10's",
  "HydroxyzineHCl Tablets IP 10 mg 10's",
  "Hyoscine Butylbromide",
  "Hyoscine Butylbromide 10mg",
  "Hyoscine Butylbromide ER",
  "Hyoscine Butylbromide SR",
  "Ibuprofen",
  "Ibuprofen 10mg",
  "Ibuprofen ER",
  "Ibuprofen SR",
  "Ibuprofenfilmcoated Tablets IP 200 mg 10's",
  "Imatinibmesylate Tablets IP 400 mg 10's",
  "Imipenem",
  "Imipenem 10mg",
  "Imipenem ER",
  "Imipenem SR",
  "IMIPENEMANDCILASTATININJ IP(500 mg+500 mg) Vial &",
  "INDAPAMIDETABLETSIP 1.5 MG 10's",
  "INFENT FEEDINGTUBE SIZE 5 FG, LENGTH 5 0 cmmin, Sterile, singlypacked inblister",
  "INFENT FEEDINGTUBE SIZE, 1 OFGLENGTH 5 0 cmmin, Sterile, singlypacked inblister",
  "INFENT FEEDINGTUBE SIZE, 8 FGLENGTH 5 0 cmmin, Sterile, singlypacked inblister",
  "Infliximab",
  "Infliximab 10mg",
  "Infliximab ER",
  "Infliximab SR",
  "Insulin Glargine",
  "Insulin Glargine 10mg",
  "Insulin Glargine ER",
  "Insulin Glargine SR",
  "Insulin Regular",
  "Insulin Regular 10mg",
  "Insulin Regular ER",
  "Insulin Regular SR",
  "InsulinGlargine 100 IUInjectionsCartridge/",
  "INSULININJECTIONIP 40 IU/ ml(InsulinHumanRecombinant)",
  "Ipratropium Bromide",
  "Ipratropium Bromide 10mg",
  "Ipratropium Bromide ER",
  "Ipratropium Bromide SR",
  "Iron & Zinc(Carbonyl Iron 50 mg+ ZincSulphateMonohydrateUSP 61.8 mgequivalent toElemental Zinc",
  "Iron Polysaccharide",
  "Iron Polysaccharide 10mg",
  "Iron Polysaccharide ER",
  "Iron Polysaccharide SR",
  "Iron Sucrose",
  "Iron Sucrose 10mg",
  "Iron Sucrose ER",
  "Iron Sucrose SR",
  "Iron(eq. toelemental iron 50 mg) + FolicAcid(0.5 mg)/ 15 ml Syrup",
  "IRONHYDROXIDEPOLYMALTOSECOMPLEX EQTOELEMENTALIRON 50 MG+ FOLICACID 0.5 MG",
  "Isosorbide Mononitrate",
  "Isosorbide Mononitrate 10mg",
  "Isosorbide Mononitrate ER",
  "Isosorbide Mononitrate SR",
  "IsosorbideDinitrate 10 mgTabs IP 10's",
  "ISOSORBIDEDINITRATETABLETSIP 5 MG 50's",
  "Isosorbidemononitrate Tablets IP 20 mg 10's",
  "Isotretinoin",
  "Isotretinoin 10mg",
  "Isotretinoin ER",
  "Isotretinoin SR",
  "IspagulaHuskPowder IP 200 gm",
  "ITOPRIDE Tablets 50 mg 10's",
  "Itraconazole",
  "Itraconazole 10mg",
  "Itraconazole ER",
  "Itraconazole SR",
  "ITRACONAZOLECapsules 100 mg 4's",
  "Ivermectin",
  "Ivermectin 10mg",
  "Ivermectin ER",
  "Ivermectin SR",
  "IVERMECTIN TABLETS 12 MG 10's",
  "Ketoconazole",
  "Ketoconazole 10mg",
  "Ketoconazole ER",
  "Ketoconazole SR",
  "KETOCONAZOLE Tablets IP 200 mg 10's",
  "KetoconazoleCream 2 % w/ w 15 gm",
  "KETOROLACTABLETSDT 10 MG 10's",
  "KIT OFMIFEPRISTONE 200 mg(1 TABLET) + MISOPROSTOL 200 mg(4 Tablets)",
  "L-LYSINE + MULTIVITAMINS(VIT -B1,B2,B3,B5,B6) SYRUP",
  "L-methylfolatecalcium 7.5 mg Tablet 10's",
  "LABETALOLINJECTIONIP 5 mg/ ml 4 ml Vial",
  "LABETALOLTABLETSIP 100 MG 10's",
  "LACTOBACILLUSSPOROGENES 60 MILLIONSPORESTABLETS",
  "Lactulose 10 gm/ 15 ml 200 ml",
  "Lactulose Syrup 10 gm/ 15 ml 100 ml",
  "Lamivudine",
  "Lamivudine 10mg",
  "Lamivudine ER",
  "Lamivudine SR",
  "Lamotrigine",
  "Lamotrigine 10mg",
  "Lamotrigine ER",
  "Lamotrigine SR",
  "Lansoprazole",
  "Lansoprazole 10mg",
  "Lansoprazole ER",
  "Lansoprazole SR",
  "Latanoprost",
  "Latanoprost 10mg",
  "Latanoprost ER",
  "Latanoprost SR",
  "laxativeSuspensionLiqidParaffin 3.75 ml +MilkofMagnesia 11.25 ml)",
  "Ledipasvir",
  "Ledipasvir 10mg",
  "Ledipasvir ER",
  "Ledipasvir SR",
  "Leflunomide Tablets IP 20 mg 10's",
  "Lenalidomide Capsules 10 mg 10's",
  "Letrozole Tablets 2.5 mg 10's",
  "Levetiracetam",
  "Levetiracetam 10mg",
  "Levetiracetam ER",
  "Levetiracetam SR",
  "LEVETIRACETAM Tablets 500 mg 10's",
  "LevetiracetamSyrup100 Mg/ 5 ml 100 ml",
  "Levo-Thyroxine Tablets IP 50 MCGIP 100'sin",
  "LEVO-THYROXINESODIUMTABLETSIP 100 MCG 100'sinA",
  "Levocetirizine",
  "Levocetirizine 10mg",
  "Levocetirizine ER",
  "Levocetirizine SR",
  "Levocetrizine 5  mg film coated Tablets IP 10's",
  "Levofloxacin",
  "Levofloxacin 10mg",
  "Levofloxacin 250  mg film coated Tablets IP 10's",
  "Levofloxacin 500  mg film coated Tablets IP 10's",
  "Levofloxacin 500 mgINFUSION/ IV 100 ml",
  "Levofloxacin ER",
  "Levofloxacin SR",
  "LevofloxacinInfusionI.P. strength 500 mg 100 ml",
  "Levonorgestrel",
  "Levonorgestrel 10mg",
  "Levonorgestrel ER",
  "Levonorgestrel SR",
  "LEVOSULPIRIDE 75 MG+ ESOMEPRAZOLE 40 MGCAPSULES",
  "LEVOSULPIRIDE 75 MG+ PANTOPRAZOLE 40 MGCAPSULE",
  "Levosulpiride Tablets 25 mg 10's",
  "LEVOSULPIRIDE(SR) 75 mg+ RABEPRAZOLE(EC) 20 mg Capsules",
  "Levothyroxine",
  "Levothyroxine 10mg",
  "Levothyroxine ER",
  "Levothyroxine Sodium",
  "Levothyroxine Sodium 10mg",
  "Levothyroxine Sodium ER",
  "Levothyroxine Sodium SR",
  "Levothyroxine SR",
  "Ligncaine 10 mg + Adrenaline 0.005 mg/ ml inj . 30 ml vial",
  "Lignocaine(Lidocaine) HydrochlorideGel IP 2 % w/v 20 g",
  "LIGNOCAINEINJECTIONIP 2 % w/v 30 ML",
  "Linagliptin",
  "Linagliptin 10mg",
  "Linagliptin ER",
  "Linagliptin SR",
  "Linezolid",
  "Linezolid 10mg",
  "Linezolid ER",
  "Linezolid SR",
  "LINEZOLIDINFUSION 600 MG/300 ML 300 ML",
  "LINEZOLIDTABLETSIP 600 MG 10's",
  "LIQUIDPARAFFIN 1.25 ML+ MILK OFMAGNESIA 3.75 ML+ SODIUMPICOSULPHATE 3.33 MG/ 5 ML",
  "Lisinopril",
  "Lisinopril 10mg",
  "Lisinopril 5 mgTabs IP 10's",
  "Lisinopril ER",
  "Lisinopril SR",
  "Lithium Carbonate",
  "Lithium Carbonate 10mg",
  "Lithium Carbonate ER",
  "Lithium Carbonate SR",
  "Loperamide",
  "Loperamide 10mg",
  "Loperamide ER",
  "Loperamide SR",
  "LOPERAMIDECapsules IP 2 mg 10's",
  "Loratadine",
  "Loratadine 10mg",
  "Loratadine ER",
  "Loratadine SR",
  "LORATIDINE TabletsBP 10 mg 10's",
  "Lorazepam Tablets IP 1 mg 10's",
  "Lorazepam Tablets IP 2 mg 10's",
  "Losartan",
  "Losartan + H.Ch. Thaizide(50 mg + 12.5 mg) filmcoated Tablets IP",
  "Losartan 10mg",
  "Losartan 25  mg film coated Tablets IP 10's",
  "LOSARTAN 50 MG+ AMLODIPINE 5 MGTABLETS 10's",
  "Losartan ER",
  "Losartan SR",
  "LosartanPotassium 50  mg film coated Tablets IP 10's",
  "Macitentan",
  "Macitentan ER",
  "Macitentan SR",
  "Magaldrate 400 mg + Simethiocone 20 mg 170 ml",
  "Magnesium Hydroxide",
  "Magnesium Hydroxide 10mg",
  "Magnesium Hydroxide ER",
  "Magnesium Hydroxide SR",
  "Mannitol",
  "Mannitol 10mg",
  "Mannitol ER",
  "Mannitol SR",
  "MANNITOLINJECTIONIP 20 % w/v 100 ml",
  "MefenamicAcid 50 mg, Paracetamol 125 mg/ 5 mlSuspension",
  "MEFENAMICACID 500 MG+ PARACETAMOL 325 MGTABLETS",
  "MEFENAMICACIDSUSPENSION 100 mg/ 5 ml 60 ml",
  "Memantine",
  "Memantine 10mg",
  "Memantine ER",
  "Memantine SR",
  "Meropenem",
  "Meropenem 1 gmInj . IPVial & wfi",
  "Meropenem 10mg",
  "Meropenem ER",
  "Meropenem SR",
  "Metformin",
  "Metformin 1000 mgSR + Glimipride 2 mg Tablet 10's",
  "Metformin 10mg",
  "Metformin ER",
  "Metformin SR",
  "Metformin(SR) 500 mg + Pioglitazone 15 mg Tablets 10 s",
  "MetforminHydrochloride 500 mgTabs IP 10's",
  "METFORMINHYDROCHLORIDESUSTAINRELEASETABLETSIP 1000 MG",
  "METFORMINHYDROCHLORIDETABLETSIPPROLONGRELEASE 500 MG",
  "MetforminSR Tablets IP 850 mg 10's",
  "Methocarbamol",
  "Methocarbamol 10mg",
  "Methocarbamol ER",
  "Methocarbamol SR",
  "Methotrexate",
  "Methotrexate 10mg",
  "Methotrexate ER",
  "Methotrexate SR",
  "Methyl Ergometrine 0.125 mgTabs IP 10's",
  "METHYLCOBALAMIN 500 MCGINJECTION 1 ML",
  "Methylergometrine",
  "Methylergometrine 10mg",
  "Methylergometrine ER",
  "Methylergometrine SR",
  "Methylprednisolone",
  "Methylprednisolone 10mg",
  "Methylprednisolone ER",
  "Methylprednisolone SR",
  "METHYLPREDNISOLONESODIUMSUCCINATEINJECTION 1000 MGPERVIAL",
  "Metoclopramide",
  "Metoclopramide 10 mgTabs IP 10's",
  "Metoclopramide 10mg",
  "Metoclopramide ER",
  "Metoclopramide SR",
  "MetoclopramideInjectionsIP 5 mg/ ml 2 ml",
  "Metoprolol",
  "Metoprolol 10mg",
  "Metoprolol 25 mgTabs IP",
  "METOPROLOL 50 MG + AMLODIPINE 5 MGTABLETS",
  "Metoprolol 50 mgTabs IP",
  "Metoprolol ER",
  "Metoprolol SR",
  "Metronidazole",
  "Metronidazole 10mg",
  "Metronidazole 5 mg/ ml Infusion 100 ml",
  "Metronidazole ER",
  "Metronidazole SR",
  "Metronidazole Tablets IP 400 mg 10's",
  "MetronidazoleFilmCoated Tablets IP 200 mg 10's",
  "Micafungin",
  "Micafungin ER",
  "Micafungin SR",
  "MIFEPRISTONE Tablets IP 200 mg 1's",
  "Minocycline",
  "Minocycline 10mg",
  "Minocycline ER",
  "Minocycline SR",
  "Minoxidil",
  "Minoxidil 10mg",
  "Minoxidil ER",
  "Minoxidil SR",
  "Mirtazapine Tablets 15 mg 10's",
  "Misoprostol",
  "Misoprostol 10mg",
  "Misoprostol 200 mcgfilmcoated Tablets IP 4's",
  "Misoprostol ER",
  "Misoprostol SR",
  "MometasoneFuroate 0.1 % w/ w 15 gm",
  "Montelukast",
  "MONTELUKAST 10 MG + FEXOFENADINEHCl 120 MGTABLETS",
  "Montelukast 10mg",
  "Montelukast ER",
  "Montelukast Sodium",
  "Montelukast Sodium + Levocetrizine(10 mg + 5 mg) filmcoated Tablets",
  "Montelukast Sodium 10 mgTab IP 10's",
  "Montelukast Sodium 10mg",
  "Montelukast Sodium 5 mgTab IP 10's",
  "Montelukast Sodium ER",
  "Montelukast Sodium SR",
  "Montelukast SR",
  "Morphine",
  "Morphine 10mg",
  "Morphine ER",
  "Morphine SR",
  "MouthUlcer Gel(CholineSalicylatesodium 9 % w/ v, BenzalkoniumChloride 0.01 % w/ w)",
  "Moxifloxacin",
  "Moxifloxacin 10mg",
  "Moxifloxacin ER",
  "Moxifloxacin SR",
  "MOXIFLOXACINTABLETS 400 MG 5's",
  "Mucodilator Expectorant TerbutalineSulphate 1.25 mg, Bromhexine 4 mg, Guaiphenesin 50 mg, Menthol 2.5 mg",
  "Multivitamin",
  "Multivitamin 10mg",
  "Multivitamin ER",
  "Multivitamin SR",
  "Mupirocin",
  "Mupirocin 10mg",
  "Mupirocin ER",
  "Mupirocin SR",
  "MUPIROCIN OINTMENT IP 2 % w/w 5 gm",
  "Mycophenolate Mofetil",
  "Mycophenolate Mofetil 10mg",
  "Mycophenolate Mofetil ER",
  "Mycophenolate Mofetil SR",
  "NANDROLONEDECANOATEINJECTIONIP 25 MG/ML",
  "NASALOXYGENCANNULA { SET }, TWINBORE { ACCESSORYFORCOMPRESSEDAIRBREATHING } ALL",
  "Nebivolol 5 mg, Hydrochlorothiazide 12.5 mgTab. 10's",
  "Nebivolol Tablets IP 10 mg 10's",
  "Needle 1 6 G(Sterile, singleuse, disposable, asper BIS) 1 's",
  "Needle 1 8 G(Sterile, singleuse, disposable, asper BIS) 1 's",
  "Needle 2 3 G(Sterile, singleuse, disposable, asper BIS) 1 's",
  "Needle 2 6 Ghalfinch(Sterile, singleuse, disposable, asper BIS) 1 's",
  "Neomycin",
  "Neomycin 10mg",
  "Neomycin ER",
  "Neomycin SR",
  "Nepafenac 0.1 % w/ vEyeDrop 5 ml",
  "Nevirapine",
  "Nevirapine 10mg",
  "Nevirapine ER",
  "Nevirapine SR",
  "NIFEDIPINEPROLONGEDRELEASE Tablets IP 20",
  "Nimesulide 1 % W/ WGel 20 Gm",
  "Nimesulide 100 mgTab IP 10's",
  "Nitazoxanide",
  "Nitazoxanide 10mg",
  "Nitazoxanide ER",
  "Nitazoxanide SR",
  "Nitrofurantoin",
  "Nitrofurantoin 10mg",
  "Nitrofurantoin ER",
  "Nitrofurantoin SR",
  "Nitrofurantoin TabletsI.P 100 mg 10's",
  "Nitroglycerin",
  "Nitroglycerin 10mg",
  "Nitroglycerin ER",
  "Nitroglycerin SR",
  "NitroglycerineInjection 5 mg/ ml 10 ml Vial",
  "NORETHISTERONE Tablets IP 5 mg 10's",
  "NORFLOXACIN 400 mg + TINIDAZOLE 600  mg film coated Tablets",
  "Nortriptyline Tablet 25 mg Tablet 10's",
  "Nystatin",
  "Nystatin 10mg",
  "Nystatin ER",
  "Nystatin SR",
  "Ofloxacin + Ornidazole(200 mg + 500 mg) filmcoated Tablets",
  "Ofloxacin 200 mg+Ornidazole 500 mginfusion 100 ml",
  "Ofloxacin 200  mg film coated Tablets IP 10's",
  "Ofloxacin 400  mg film coated Tablets IP 10's",
  "OfloxacinEyeDrops 0.3 % w/ v 10 ml",
  "OFLOXACININFUSIONIP 200 mg/ 100 ml 100 ml",
  "Olanzapine",
  "Olanzapine 10mg",
  "Olanzapine ER",
  "Olanzapine SR",
  "Olanzapine TabletsI.P 10 mg 10's",
  "Olanzapine TabletsI.P 5 mg 10's",
  "OLMESARTAN 20 mg+ AMLODIPINE 5 mg Tablets 10's",
  "Olmesartan Tablets 20 mg 10's",
  "OLMESARTAN Tablets 40 mg 10's",
  "OLMESARTANMEDOXOMIL 40 mg + HYDROCLORTHIAZIDE 12.5 mg Tablets",
  "OlopattadineEyeDrops 10 ml Vial",
  "Omalizumab",
  "Omalizumab 10mg",
  "Omalizumab ER",
  "Omalizumab SR",
  "Omega-3",
  "Omega-3 10mg",
  "Omega-3 ER",
  "Omega-3 SR",
  "Omeprazole",
  "Omeprazole + Domperidone(20 mg + 10 mg) Caps 10's",
  "Omeprazole 10mg",
  "Omeprazole 20 mgcapsuls IP 10's",
  "Omeprazole ER",
  "Omeprazole Magnesium",
  "Omeprazole Magnesium 10mg",
  "Omeprazole Magnesium ER",
  "Omeprazole Magnesium SR",
  "Omeprazole SR",
  "Ondansetron",
  "Ondansetron 10mg",
  "Ondansetron 4 mgTabs IP 10's",
  "Ondansetron ER",
  "Ondansetron SR",
  "OndansetronOral SolutionI.P 2 mg/ 5 ml 30 ml",
  "ONDENSETRONINJECTIONIP 2 mg/ ml 2 ML",
  "Oral Contraceptive Pill",
  "Oral Contraceptive Pill 10mg",
  "Oral Contraceptive Pill ER",
  "Oral Contraceptive Pill SR",
  "Oral RehydrationSaltsCitrateIP 21 GM(WHOFormula) Sachet IP",
  "Ornidazole 500  mg film coated Tablets IP 10's",
  "OxaliplatinInjections 50 mgVial",
  "Oxcarbazepine TabletsI.P 300 mg 10's",
  "OXETACAINE 10 MG+ ALUMINIUM 0.291 MG + MAGNESIUM 98 MG/ 5 MLGEL",
  "Oxycodone",
  "Oxycodone 10mg",
  "Oxycodone ER",
  "Oxycodone SR",
  "OXYMETAZOLINE 0.5 MG/ MLNASALDROPS 10 ML",
  "Oxytocin",
  "Oxytocin 10mg",
  "Oxytocin ER",
  "Oxytocin SR",
  "OXYTOCININJECTIONIP 5 iu/ ml 1 ML",
  "Paclitaxel Injection 100 mgVial",
  "Palonosetron",
  "Palonosetron 10mg",
  "Palonosetron ER",
  "Palonosetron SR",
  "Pantoprazole",
  "Pantoprazole 10mg",
  "Pantoprazole 40 mg + Itopride 150 mgS.R. 10's",
  "Pantoprazole 40 mgentericcoated Tablets IP 10's",
  "Pantoprazole 40 mgInj . vial",
  "Pantoprazole ER",
  "Pantoprazole Sodium",
  "Pantoprazole Sodium 10mg",
  "Pantoprazole Sodium ER",
  "Pantoprazole Sodium SR",
  "Pantoprazole SR",
  "Paper AdhesivePlaster 1 \\",
  "Paper AdhesivePlaster 2 \\",
  "Paper AdhesivePlaster 3 \\",
  "Paracetamol",
  "Paracetamol + DiclofenacSodium(325 mg + 50 mg) Tab 10's",
  "Paracetamol 10mg",
  "Paracetamol 125 mg+ CPM 1 mg + SodiumCitrate 60 mgina flavour syrupbase",
  "Paracetamol 125 mg/ 5 ml Syrup IP 60 ml",
  "PARACETAMOL 325 mg+ TRAMADOL 37.5 mg Tablets",
  "PARACETAMOL 500 mg+ PHENYLEPHRINE 10 mg+ CHLORPHENIRAMINE 2 mg Tablets",
  "Paracetamol 500 mgTab IP 10's",
  "Paracetamol DSsyrup/ 250 mg 60 ml",
  "Paracetamol ER",
  "Paracetamol I.P. 125 mg: 15 ml",
  "Paracetamol SR",
  "PARACETAMOL Tablets IP 650 mg 15's",
  "PEPSIN 10 MG+ DIASTASE 50 MGORALLIQUID/ 5",
  "PermethrinCream 5 % w/ w 30 gm",
  "PHENIRAMINE Tablets IP 25 mg 15's",
  "PheniramineMaleateI.P. 22.75 mg,Methyl Paraben(aspreservative) I.P. 0.135 % w/v, Propyl Paraben(as",
  "Phenobarbital",
  "Phenobarbital 10mg",
  "Phenobarbital ER",
  "Phenobarbital SR",
  "Phenobarbitone TabletsI.P 30 mg 30's",
  "Phenoxymethylpenicillin",
  "Phenoxymethylpenicillin 10mg",
  "Phenoxymethylpenicillin ER",
  "Phenoxymethylpenicillin SR",
  "PhenylephrineHydrochloride 5.00 mgChlorpheniranmineMaleate 2.00 mgDrops",
  "Phenytoin",
  "Phenytoin 10mg",
  "Phenytoin ER",
  "Phenytoin SR",
  "PHENYTOIN Tablets IP 100 mg 100'sin",
  "Pilocarpine",
  "Pilocarpine 10mg",
  "Pilocarpine ER",
  "Pilocarpine SR",
  "Pioglitazone",
  "Pioglitazone 10mg",
  "Pioglitazone 15 mgTabs 10's",
  "Pioglitazone ER",
  "Pioglitazone SR",
  "Pioglitazone TabletsI.P. strength 30 mg 10 s",
  "Piracetam Tablets 400 mg 10's",
  "PiracetamSyrup 500 mg/ 5 ml 100 ML",
  "Piroxicam 20 mgbtablets 10's",
  "Piroxicam 20 mgwithbezyl alcohol injection 1 ml",
  "Piroxicam 40 mgwithbezyl alcohol injection 2 ml",
  "PIROXICAMCapsules IP 20 mg 10's",
  "Plaster ofParisBandagesBP 1 0 cmX 2 . 7 mts/ RollOne",
  "Plaster ofParisBandagesBP 1 5 cmX 2 . 7 mts/ RollOne",
  "POLYAMIDE { 3/8 } cir slimbladecuttingneedle 1 5 mmlength 7 0 cm }",
  "POLYAMIDE { 3/8 } conventionalcuttingneedle 1 9 mmlength 6 0 cm",
  "POLYAMIDE { 3/8 } cuttingspatulated edgeneedle, doublearmneedle 6 mm, suture 3 0 - 4 2 cm,",
  "Polyamide(3/8 Cir MicropointRound Body, 6 mmLength 3 8 cm)",
  "Polyamide(3/8 Cir RCuttingNeedle 4 5 mmLength 7 0 cm.) One",
  "Polyamide(3/8 ConventionalCuttingNeedle 1 6 mmLength 7 0 cm)",
  "POLYBUTYLATE/ SILICONCOATEDPOLYSTERBRAIDEDGREEN/ BLUE { 1/2 cir Tapercut, 1 7 mmdouble",
  "POLYBUTYLATE/ SILICONCOATEDPOLYSTERBRAIDEDgreen/ blue { 1/2 cir Tapercut, 1 7 mmdoubleneedle",
  "POLYBUTYLATE/ SILICONCOATEDPOLYSTERBRAIDEDGREEN/ BLUE { 1/2 cir Tapercut, 2 5 mmdouble",
  "POLYBUTYLATE/ SILICONCOATEDPOLYSTERBRAIDEDwhite { 1/2 cir Tapercut, 1 7 mmdoubleneedle",
  "Polyglecaprone/ 1/2 circleovalRB neele 2 6 mm, needle, suturelengthof 7 0 cm. }",
  "Polyglecaprone/Polyglyconate(3/8 CircleCutting 2 5 mmNeedle, SutureLengthof 7 0 cm)",
  "Polyglecaprone/Polyglyconate(l/2 CircleOvalRB ContrastNeedle 2 6 mm, suturelength 7 0 cm)",
  "Polymyxin B",
  "Polymyxin B 10mg",
  "Polymyxin B ER",
  "Polymyxin B SR",
  "POLYPROPYLENE { 1/2 Cir CC 1 3 mmneedle, SUTURELENGHOF 7 0 cmDOUBLE ARM.",
  "POLYPROPYLENE { 1/2 Cir RB 1 3 mmneedle, length 7 5 cmDOUBLE Arm",
  "POLYPROPYLENE { 1/2 Cir RB 2 5 mmneedleSUTURElength 7 5 cmDOUBLE ARM.",
  "POLYPROPYLENE { 1/2 Cir RB DOUBLE needle 1 6 mmlength 9 0 cm",
  "POLYPROPYLENE { 1/2 Cir RB DOUBLE needle 1 7 mmlength 9 0 cm",
  "POLYPROPYLENE { 1/2 Cir RB heavyneedle 4 5 mmlength 9 0 cm",
  "POLYPROPYLENE { 1/2 Cir RB needle 3 0 mmlength 9 0 cm } One",
  "POLYPROPYLENE { 1/2 Cir REVERCE CUTTINGneedle 4 5 mmlength 1 0 0 cm",
  "POLYPROPYLENE { 1/2 Cir Tapercutdoubleneedle 2 5 mmleanth 9 0 cm} DOUBLE ARM",
  "POLYPROPYLENE { 1/2 CirCLE TAPERCUT 1 7 mmneedle, SUTURE LENGHOF 9 0 cmDOUBLE ARM.",
  "POLYPROPYLENE { 3/8 Cir CONVENTIONALCUTTINGPC-3 NEEDLE 1 5 MM LENGTH 6 0 CM}",
  "POLYPROPYLENE { 3/8 Cir CUUTTINGneedlelength 2 5 cmLENGTH 4 5 CM",
  "POLYPROPYLENE { 3/8 Cir RB 1 3 mmneedlelength 9 0 cmDOUBLE ARM",
  "POLYPROPYLENE { 3/8 Cir RB 1 6 mmneedlelength 7 0 cmOne",
  "POLYPROPYLENE { 3/8 Cir RB 8 mmDOUBLE needleSUTURE length 7 0 cm",
  "POLYPROPYLENE { 3/8 Cir RB DOUBLE 8 mmneedle 6 0 cmOne",
  "PolypropyleneNonabsorbableSyntheticSurgicalMesh 1 5 cmX 1 5 cm",
  "PolypropyleneNonabsorbableSyntheticSurgicalMesh 7 . 5 cmX 1 5 cm",
  "Polyvitamin(Prophylactic) NFIfilmcoated Tablets 10's",
  "Posaconazole",
  "Posaconazole ER",
  "Posaconazole SR",
  "PovidoneIodine 10 % Solution IP 500 ml",
  "PovidoneIodine 5 % Solution IP 500 ml",
  "PovidoneIodine 5 % w/ wOintment USP 15 gm",
  "PovidoneIodine 5 % w/ wOintment USP 250 gm",
  "PovidoneIodine 7.5 % Solution IP 500 ml",
  "Povidonelodine 5 % Solution 100 ml 100 ml",
  "Pramipexole",
  "Pramipexole 10mg",
  "Pramipexole ER",
  "Pramipexole SR",
  "Praziquantel",
  "Praziquantel 10mg",
  "Praziquantel ER",
  "Praziquantel SR",
  "PRAZOSINTABLETSIP 5 MG 15's",
  "Prednisolone",
  "Prednisolone 10 mgTabs IP 10's",
  "Prednisolone 10mg",
  "Prednisolone ER",
  "Prednisolone SR",
  "Prednisolone Tablets IP 5 MG 15's",
  "Prednisone",
  "Prednisone 10mg",
  "Prednisone ER",
  "Prednisone SR",
  "Pregabalin",
  "Pregabalin 10mg",
  "PREGABALIN 75 mg+ METHYLCOBALAMIN 750 MCG Tablets",
  "Pregabalin ER",
  "Pregabalin SR",
  "PregabalinCapsules 75 mg 14's",
  "PREGABALINTABLETS 75 MG 10's",
  "PRIMAQUINETABLETSIP 15 MG 10's",
  "Prochlorperazine",
  "Prochlorperazine 10mg",
  "Prochlorperazine 5 mgTabs IP",
  "Prochlorperazine ER",
  "Prochlorperazine SR",
  "ProchlorperazineMaleate TabletsI.P 5 mg 10's",
  "Progesterone",
  "Progesterone 10mg",
  "Progesterone ER",
  "Progesterone SR",
  "Promethazine",
  "Promethazine 10mg",
  "Promethazine ER",
  "Promethazine SR",
  "PROMETHAZINE(FILMCOATED) Tablets IP 25 mg 10's",
  "PromethazineInjectionI.P 25 mg/ ml 2 ml",
  "Propofol 10 mg/ ml Inj 10 ml vial",
  "Propranolol",
  "Propranolol 10mg",
  "Propranolol ER",
  "Propranolol SR",
  "Propranolol Tablets IP 10 mg 10's",
  "PROPRANOLOL Tablets IP 40 mg 10's",
  "Pyrazinamide TabletsI.P 1000 mg 10's",
  "PYRIDOXINEHCl 10 mg+ DOXYLAMINE 10 mg + FOLICACID 2.5 mg Tablets",
  "Quetiapine",
  "Quetiapine 10mg",
  "Quetiapine ER",
  "Quetiapine SR",
  "Quetiapine TabletsI.P 100 mg 10's",
  "QuetiapineFumarate TabletsI.P 200 mg 10's",
  "QUININESULPHATE TABLETSIP 300  mg film coatedTABLETS",
  "Rabeprazole + DomperidoneSR(20 mg + 30 mg) caps. 10's",
  "Rabeprazole 20 mg + Domperidone 10 mg 10's",
  "Rabeprazole 20 mgentericcoated Tablets IP 10's",
  "RabeprazoleSodiumip 20 mg + ItopirideHCL 150 mg 10's",
  "Raltegravir",
  "Raltegravir 10mg",
  "Raltegravir ER",
  "Raltegravir SR",
  "Ramipril",
  "Ramipril 10mg",
  "Ramipril 2.5 mgTabs IP",
  "Ramipril 5 mgTabs IP",
  "Ramipril ER",
  "Ramipril SR",
  "RAMIPRILandHYDROCLORTHIAZIDETABLETSIP(5 MG+12.5 MG)",
  "Ranitidine",
  "Ranitidine 10mg",
  "Ranitidine ER",
  "Ranitidine SR",
  "RANITIDINE Tablets IP 300  mg film coated 10's",
  "RanitidineHCl . 150  mg film coated Tablets IP 10's",
  "RANITIDINEINJECTIONIP 50 MG/ 2 ML 2 ML",
  "RavlonSolution(Chlorhexidine + Cetramide)(1.5 % w/ v + 3 % w/ v) Solution",
  "Repaglinide",
  "Repaglinide 10mg",
  "Repaglinide ER",
  "Repaglinide SR",
  "Ribavirin",
  "Ribavirin 10mg",
  "Ribavirin ER",
  "Ribavirin SR",
  "RifampicinandIsoniazide Tablets IP(450 MG+300 MG) 10's",
  "Ringer Lactate 500 ml IV",
  "Riociguat",
  "Riociguat ER",
  "Riociguat SR",
  "Risperidone",
  "Risperidone 10mg",
  "Risperidone ER",
  "Risperidone SR",
  "Risperidone Tablets 4 mg 10's",
  "Ritonavir",
  "Ritonavir 10mg",
  "Ritonavir ER",
  "Ritonavir SR",
  "Rituximab",
  "Rituximab 10mg",
  "Rituximab ER",
  "Rituximab SR",
  "Rivastigmine",
  "Rivastigmine 10mg",
  "Rivastigmine ER",
  "Rivastigmine SR",
  "Ropinirole",
  "Ropinirole 10mg",
  "Ropinirole ER",
  "Ropinirole SR",
  "Rosiglitazone",
  "Rosiglitazone 10mg",
  "Rosiglitazone ER",
  "Rosiglitazone SR",
  "ROSUVASTATIN 10 mg + FENOFIBRATES 160 mg Tablets",
  "Rosuvastatin Tablet 10 mg 15's",
  "Rosuvastatin Tablet I.P 5 mg 10's",
  "ROSUVASTATIN Tablets IP 20 mg 10's",
  "Roxithromycin 150  mg film coated Tablets IP 10's",
  "Roxithromycin TabletsI.P. filmcoatedstrength 300 mg 10 s",
  "RoxithromycinSuspensionstrength 50 mg/ 5 ml 30 ml",
  "RYLE \\",
  "S-AMLODIPINETABLETSIP 2.5 MG 10's",
  "Salbutamol",
  "Salbutamol 10mg",
  "SALBUTAMOL 2 MG 10's",
  "Salbutamol ER",
  "Salbutamol Nebule",
  "Salbutamol Nebule 10mg",
  "Salbutamol Nebule ER",
  "Salbutamol Nebule SR",
  "Salbutamol SR",
  "Salbutamol Syrup IP 2 mg/ 5 ml 100 ml",
  "Salbutamol Tablets IP 4 mg 10's",
  "Salicylic Acid",
  "Salicylic Acid 10mg",
  "Salicylic Acid ER",
  "Salicylic Acid SR",
  "Saquinavir",
  "Saquinavir 10mg",
  "Saquinavir ER",
  "Saquinavir SR",
  "Saxagliptin",
  "Saxagliptin 10mg",
  "Saxagliptin ER",
  "Saxagliptin SR",
  "Scalp VeinSet(Disposable) Size 1 8 GSterile, Soft, kinkresistant, non-toxic, nonirritanttube",
  "Scalp VeinSet(Disposable) Size 2 0 G, Sterile, Soft, kinkresistant, non-toxic, nonirritanttube",
  "Scalp VeinSet(Disposable) Size 2 2 G, Sterile, Soft, kinkresistant, non-toxic, nonirritanttube",
  "Scalp VeinSet(Disposable) Size 2 4 GSterile, Soft, kinkresistant, non-toxic, nonirritanttube",
  "Selegiline",
  "Selegiline (oral)",
  "Selegiline (oral) 10mg",
  "Selegiline (oral) ER",
  "Selegiline (oral) SR",
  "Selegiline 10mg",
  "Selegiline ER",
  "Selegiline SR",
  "Serratiopeptidase Tablets 10 mg 10's",
  "Sertraline",
  "Sertraline 10mg",
  "Sertraline ER",
  "Sertraline SR",
  "Sertraline Tablets 50 mg 10's",
  "Sertraline TabletsI.P 100 mg 10's",
  "Sertraline TabletsI.P 25 mg 10's",
  "Sildenafil",
  "Sildenafil (pulm hypertension)",
  "Sildenafil (pulm hypertension) ER",
  "Sildenafil (pulm hypertension) SR",
  "Sildenafil 10mg",
  "Sildenafil ER",
  "Sildenafil SR",
  "Sildenafil Tablets 100 mg 4's",
  "SILDENAFIL Tablets IP 50 mg 4's",
  "silk { 3/8 cir RB NEEDLE 1 6 MM, LENGTH 7 6 cm } One",
  "silk { 3/8 cir RB NEEDLE 2 0 MM, LENGTH 7 6 cm } One",
  "silk { 3/8 cir ReverseCUTTINGNEEDLE 2 6 MM, LENGTH 7 6 cm }",
  "silk { 3/8 cir ReverseCUTTINGNEEDLE 4 5 MM, LENGTH 7 6 cm }",
  "Simeprevir",
  "Simeprevir 10mg",
  "Simeprevir ER",
  "Simeprevir SR",
  "Simvastatin",
  "Simvastatin 10mg",
  "Simvastatin ER",
  "Simvastatin SR",
  "Simvastatin TabletsI.P. strength 10 mg 10 s",
  "Simvastatin TabletsI.P. strength 20 mg 10 s",
  "Sitagliptin",
  "Sitagliptin 10mg",
  "Sitagliptin ER",
  "Sitagliptin SR",
  "Sitagliptin/Metformin",
  "Sitagliptin/Metformin 10mg",
  "Sitagliptin/Metformin ER",
  "Sitagliptin/Metformin SR",
  "SODIUMCHLORIDE 0.65 % w/vNASALDROPS 20 ml",
  "SODIUMPICOSULPHATE 10 mg Tablets 10's",
  "SodiumValproate Tablets 300 mg 10's",
  "SodiumValproateEC TabletsI.P 200 mg 10's",
  "Sofosbuvir",
  "Sofosbuvir 10mg",
  "Sofosbuvir ER",
  "Sofosbuvir SR",
  "Spironolactone",
  "Spironolactone (derm use)",
  "Spironolactone (derm use) 10mg",
  "Spironolactone (derm use) ER",
  "Spironolactone (derm use) SR",
  "Spironolactone 10mg",
  "Spironolactone ER",
  "Spironolactone SR",
  "SPIRONOLACTONETABLETS IP 25 MG 15's",
  "SterileCatheter, SingleUse, for UrinaryDrainage(FoleyBalloonCatheter), 2 Way, 2 4 FG, conformto BP, Balloon",
  "SterileCatheter, SingleUse, for UrinaryDrainage(FoleyBalloonCatheter), 2 Way, Size 1 0 FG,conformto BP, Balloon",
  "SterileCatheter, SingleUse, for UrinaryDrainage(FoleyBalloonCatheter), 2 Way, Size 2 0 FG,conformto BP, Balloon",
  "SterileCatheter, SingleUse, for UrinaryDrainage(FoleyBalloonCatheter), 2 Way, Size 8 FG,conformto BP, Balloon",
  "SterileCatheter, SingleUse, for UrinaryDrainage(FoleyBalloonCatheter), 2 Way, Size, 1 6 FG,, conformto BP, Balloon",
  "SterileCatheter, SingleUse, for UrinaryDrainage(FoleyBalloonCatheter), 2 Way, Size, 1 8 FG,conformto, Balloon",
  "SterileCatheter, SingleUse, for UrinaryDrainage(FoleyBalloonCatheter), 2 Way, Size, 2 2 FG, conformto BP, Balloon",
  "SterileDisposable(SingleUse) Teflon/ PTFEI . V. Cannulawithintegrated . Size 2 4 Gsuitablefor paediatric & neonataluse",
  "SterileDisposable(SingleUse) Teflon/ PTFEI . V. Cannulawithintegrated 3 Waystop cock. Size 1 8 G",
  "SterileDisposable(SingleUse) Teflon/ PTFEI . V. Cannulawithintegrated 3 Waystop cock. Size 2 0 G",
  "SterileDisposable(SingleUse) Teflon/ PTFEI . V. Cannulawithintegrated 3 Waystop cock. Size 2 2 G)",
  "steriledisposableinfusionsetwithmicrodrip {I . V. },, 1 5 0 cmlongsmoothkinkresistanttubing",
  "steriledisposableperfusionset { infusionset } withairwayandneedle { paediatricuse } softand smoothkinkresistantPVC",
  "steriledisposableperfusionsetwithairwayand needle { adultuse }, 1 5 0 cmlongsmoothkinkresistanttubing, 2 1 Gneedle,",
  "SterileDisposableSpinalNeedlefor SingleUse 2 2 Gx 3 inchOne",
  "SterileDisposableSpinalNeedlefor SingleUse 2 5 Gx 3 inchOne",
  "sterilized umbilicalcottontapewidth 3 mm, length 7 5 cmOne",
  "STREPTOKINASEINJECTIONIP 1500000 IU 10 ml &",
  "Sucralfate",
  "Sucralfate 1 gmWithOxetacain 10 mg/ 10 ml Suspension 100 ml",
  "Sucralfate 10mg",
  "Sucralfate ER",
  "Sucralfate SR",
  "SUCRALFATESUSPENSION 500 mg/ 5 ml 200 ml",
  "SUCTIONCATHETER, STERILE SIZE, FG 1 2, Length 5 0 cm(min.)",
  "SUCTIONCATHETER, STERILE SIZE, FG 1 4, Length 5 0 cm(min.)",
  "SUCTIONCATHETER, STERILE SIZE, FG 1 6, Length 5 0 cm(min.)",
  "SUCTIONCATHETER, STERILE SIZE, FG 2 0, Length 5 0 cm(min.)",
  "SUCTIONCATHETER, STERILE SIZE, FG 5 Length 5 0 cm(min.)",
  "SUCTIONCATHETER, STERILE SIZE, FG 6 Length 5 0 cm(min.)",
  "SUCTIONCATHETER, STERILE SIZE, FG, 1 0, Length 5 0 cm(min.)",
  "SUCTIONCATHETER, STERILE SIZE, FG, 1 8, Length 5 0 cm(min.)",
  "SUCTIONCATHETER, STERILE SIZE, FG, 2 2 Length 5 0 cm(min.)",
  "SUCTIONCATHETER, STERILE SIZE, FG, 8, Length 5 0 cm(min.)",
  "Sulfacetamideeyedrop 10 % 10 ml",
  "Sulfacetamideeyedrop 20 % 20 ml",
  "SULFASALAZINETABLETSECBP 500 MG 10's",
  "SURGICALCAP, DISPOSABLE { FORSURGEONS/ NURSES }, Should bemanufactured fromnonwovenfabric",
  "Syringe 1 0 mlwithneedle 2 1 G(Sterile, singleuse, disposable, asper BIS)",
  "Syringe 2 0 mlwithneedle 2 3 G(Sterile, singleuse, disposable, asper BIS)",
  "Syringe 2 mlwithneedle 2 4 G(Sterile, singleuse, disposable, asper BIS)",
  "Syringe 5 mlwithneedle 2 4 G(Sterile, singleuse, disposable, asper BIS)",
  "Syrup - Cefuroxime 125 mg(asCefuroximeAxetil USP) 30 ml",
  "SyrupVitaminD3 200 IU + VitaminB12 2.5 mcg + CalciumPhosphateeq. toelemental Calcium 82 mg/ 5 ml",
  "Tacrolimus",
  "Tacrolimus 10mg",
  "Tacrolimus ER",
  "Tacrolimus SR",
  "Tadalafil",
  "Tadalafil (pulm)",
  "Tadalafil (pulm) ER",
  "Tadalafil (pulm) SR",
  "Tadalafil 10mg",
  "Tadalafil ER",
  "Tadalafil SR",
  "TADALAFIL Tablets 20 mg 4's",
  "TamoxifenCitrate Tablets I.P. strength 10 mg 10 s",
  "TamoxifenCitrate TabletsI.P. strength 20 mg 10 s",
  "TAMSULOSIN 0.4 MG + DUTASTERIDE 0.5 MGTABLETS",
  "TamsulosinModified-Release Capsules 0.4 mg 10's",
  "Telmisartan + Hydrochlorthiazide(40 mg + 12.5 mg) Tabs",
  "TELMISARTAN 40 mg+ CHLORTHALIDONE 12.5 mg Tablets",
  "Telmisartan 40 mgTabs IP",
  "Telmisartan 80 mg, Hydroclorthiazide 12.5 mg Tablets 10's",
  "TELMISARTAN Tablets IP 20 mg 10's",
  "Telmisartan+Metoprolol(50/ 40 mg) Tablets 10's",
  "TELMISARTANIP 40 mg+ AMLODIPINE 5 mg Tablets 15's",
  "TemporaryCardiacPacingWire(Electrode) SterileCir, Tapercut, 2 6 mmneedlewithselfretainingsystem",
  "TeneligliptinFilmcoatedtablets 20 mg 10's",
  "Tenofovir",
  "Tenofovir 10mg",
  "Tenofovir ER",
  "Tenofovir SR",
  "Terbinafine",
  "Terbinafine 10mg",
  "TERBINAFINE 250 MGTABLETS 7's",
  "Terbinafine ER",
  "Terbinafine SR",
  "Terbutaline",
  "Terbutaline 10mg",
  "TERBUTALINE 2.5 MG + BROMHEXINE 8 MG/ 10 MLSYRUP",
  "Terbutaline ER",
  "Terbutaline SR",
  "Tetracycline",
  "Tetracycline 10mg",
  "Tetracycline ER",
  "Tetracycline SR",
  "Theophylline",
  "Theophylline 10mg",
  "Theophylline 25.3 mg+ Etophylline 84.7 mg/ 2 mlInjections",
  "Theophylline ER",
  "Theophylline SR",
  "THIOCOLCHICOSIDE 4 mg+ ACECLOFENAC 100 mg Tablets",
  "Thyroxine",
  "Thyroxine 10mg",
  "Thyroxine ER",
  "Thyroxine SR",
  "THYROXINESODIUMTABLETSIP 50 µg 10's",
  "Timolol Eye Drop",
  "Timolol Eye Drop 10mg",
  "Timolol Eye Drop ER",
  "Timolol Eye Drop SR",
  "Timolol Maeleate 0.5 % EyeDrops 5 ml Vial",
  "Tinidazole 300  mg film coated Tablets 10 s",
  "Tinidazole 500  mg film coated Tablets IP 10's",
  "Tiotropium",
  "Tiotropium 10mg",
  "Tiotropium ER",
  "Tiotropium SR",
  "Tizanidine",
  "Tizanidine 10mg",
  "Tizanidine ER",
  "Tizanidine SR",
  "TobramycinEyeDrops 10 ml Vial",
  "Topiramate",
  "Topiramate 10mg",
  "Topiramate ER",
  "Topiramate SR",
  "TORASEMIDE Tablets 10 mg 15's",
  "TORASEMIDETABLETS 20 MG 10's",
  "TRACHEOSTOMYTUBE {PVC}, CUFFED, STERILE, SINGLE USE . ALLSIZE ., Softflexibleflangeatfor easy",
  "TRACHEOSTOMYTUBE {PVC}, PLAIN, STERILE, Singleuseallsize, Softflexibleflangeatfor easyfixation, 1 5 mm",
  "Tramadol",
  "Tramadol 10mg",
  "Tramadol ER",
  "Tramadol Hydrochloride 50 mg/ ml Inj . 1 ml",
  "Tramadol Hydrochloride 50 mg/ ml Inj . 2 ml",
  "Tramadol Hydrochloride 50 mgTab 10's",
  "Tramadol SR",
  "TRAMADOLTABLETSSR 100 MG 10's",
  "Tranexamic Acid",
  "Tranexamic Acid 10mg",
  "Tranexamic Acid ER",
  "Tranexamic Acid SR",
  "TRANEXAMICACID 100 MG/ ML injection 5 ML",
  "TRANEXAMICACID 500 mg+ MEFENAMICACID 250 mg Tablets",
  "TranexamicAcid 500 mgTabs IP",
  "Travoprost",
  "Travoprost 10mg",
  "Travoprost ER",
  "Travoprost SR",
  "Tretinoin",
  "Tretinoin 10mg",
  "Tretinoin ER",
  "Tretinoin SR",
  "Triamcinolone",
  "Triamcinolone 10mg",
  "Triamcinolone ER",
  "Triamcinolone SR",
  "TRICHOLINECITRATE 275 mg+ CYPROHEPTADINEHCl 2 mg/ 5 ml SYRUP",
  "TRICHOLINECITRATE 550 MG + SORBITOL 7.15 GMSYRUP/10 ML",
  "TrimceloneAcetonide 0.1 % MouthUlcer gel 10 gm",
  "UMBILICALCATHETER { FORNEW BORN } ALLSIZE, Withfemaleflexiblemount, Opentip should besoft, rounded,",
  "Urea IP 1 % + SalicylicAcidIP 1 % w/wZincSulphate 0.1 % w/ w",
  "URINE COLLECTINGBAGFORNEW BORN/ PAEDIATRICURINE COLLECTINGBAGShould have",
  "UrineCollectingBag, Disposable, 2 0 0 0 ml, Kinkresistantflexibletubingnotlessthan 9 0 cminlength, Should havenon-",
  "URSODEOXYCHOLICACID Tablets IP 300 mg 10's",
  "VACCINE RABIESINJECTION 2.5 IU 1 ml",
  "Valacyclovir",
  "Valacyclovir 10mg",
  "Valacyclovir ER",
  "Valacyclovir SR",
  "Valproate",
  "Valproate 10mg",
  "Valproate ER",
  "Valproate SR",
  "VALSARTANTABLETSIP 80 MG IP 10's",
  "Vancomycin",
  "Vancomycin 10mg",
  "Vancomycin ER",
  "Vancomycin SR",
  "VANCOMYCININTRAVENOUSINFUSION IP 500",
  "VecuroniumBromideInjectionI.P 4 mgVial",
  "Venlafaxine",
  "Venlafaxine 10mg",
  "Venlafaxine ER",
  "Venlafaxine SR",
  "Verapamil",
  "Verapamil 10mg",
  "Verapamil ER",
  "Verapamil SR",
  "Vitamin B12",
  "Vitamin B12 10mg",
  "Vitamin B12 ER",
  "Vitamin B12 SR",
  "Vitamin D3",
  "Vitamin D3 10mg",
  "Vitamin D3 ER",
  "Vitamin D3 SR",
  "VITAMINB-VOMPLEX SyrupNFI 200 ML",
  "VITAMINB1 10 MG, B2 10 MG, NIACINAMIDE 45 MG, CALCIUMPANTOTHENATE 50 MG, B6 3 MG",
  "VITAMINB6 TABLETSIP 50 MG 10's",
  "VITAMINBCOMPLEX(B1,B2,B6,B12) & VIT . CWITHZINC 22.5 MGCAPSULES",
  "VITAMIND - CHOLECALCIFEROL 60000 IU/ 1 GMSachet",
  "VitaminE Softgel Capsules 400 MG 10's",
  "VITAMINSA,C,D,E,ANDBCOMPLEX ANDMINERALSSYRUP",
  "Voglibose 0.2 mg, Metformin 500 mg Tablets 10's",
  "Voglibose 0.3 mg, Metformin 500 mg Tablets 10's",
  "VOGLIBOSE Tablets IP 0.2 mg 10's",
  "VOGLIBOSE Tablets IP 0.3 mg 10's",
  "Voriconazole",
  "Voriconazole ER",
  "Voriconazole SR",
  "Warfarin",
  "Warfarin 10mg",
  "Warfarin ER",
  "Warfarin SR",
  "WARFARINTABLETSIP 5 MG 10's",
  "Water for Injectionamppolypack 10 ml",
  "Xylometazoline 0.1 % w/ vNasal Drop IP 10 ml",
  "Zidovudine",
  "Zidovudine 10mg",
  "Zidovudine ER",
  "Zidovudine SR",
  "ZINCSULPHATE 20 MG/ MLORALSOLUTION 15 ML",
  "Zolpidem",
  "Zolpidem 10mg",
  "Zolpidem ER",
  "Zolpidem SR",
  "Zolpidem TabletsI.P 10 mg 10's",
  "€ginsengextract 42.5 mg, vitaminA 2500 IU, vitaminB1 1 mg, vitaminB2 1.5 mg, vitaminB6 1 mg, vitaminB12 1",
];

window.meds_10000 = allMedsCombined.map(function(n){
  var strengthMatch = n.match(/(\d+(?:\.\d+)?\s?(?:mg|g|gm|ml|mcg|µg|%|IU|IU\/ml))/i);
  var formMatch = n.match(/\b(Tablets|Tablet|Tab|Capsules|Capsule|Cap|Syrup|Injection|Inj|Vial|Bottle|Cream|Ointment|Gel|Sachet|Powder|Solution|Drops|Drop|Lotion|Spray|Inhaler)\b/i);
  return { name: n, strength: strengthMatch?strengthMatch[1]:'', form: formMatch?formMatch[1].toLowerCase():'' };
});

// ======= Stronger cleaner (run now) =======
(function(){
  // helper: common unit list & word tokens
  const UNITS = ['mg','g','gm','ml','mcg','µg','iu','iu/ml','%','mcg','iu/ml','iu'];
  const FORMS = ['tablets','tablet','tab','capsules','capsule','cap','syrup','injection','inj','vial','bottle','cream','ointment','gel','sachet','powder','solution','drops','drop','lotion','spray','inhaler','filmcoated','entericcoated','sr','cr','er'];

  function normalizeMicroSigns(s){
    return s.replace(/\u00B5/g,' mcg').replace(/µ/g,' mcg');
  }

  function spaceAroundPunct(s){
    // make safe spaces around + / & , { } ( ) : ; - but keep decimal dots
    s = s.replace(/([+\/*&=<>])/g,' $1 ');
    s = s.replace(/([{}\[\]\(\)])/g,' $1 ');
    s = s.replace(/([,:;])/g,'$1 ');
    // ensure space after closing punctuation if stuck to words
    return s;
  }

  function splitLettersNumbers(s){
    // Letter followed by number -> insert space
    s = s.replace(/([A-Za-z%°])([0-9])/g,'$1 $2');
    // Number followed by letter -> insert space
    s = s.replace(/([0-9])([A-Za-z%°µµ̇])/g,'$1 $2');
    return s;
  }

  function fixUnits(s){
    // Normalize unit tokens like 500mg -> 500 mg (case-insensitive)
    UNITS.forEach(function(u){
      const re = new RegExp('(\\d(?:[\\d\\.]*))\\s*(' + u.replace('/','\\/') + ')\\b','ig');
      s = s.replace(re, function(_, num, unit){ return num + ' ' + unit.toLowerCase(); });
    });
    // Also common combined forms: 500mg+125mg -> 500 mg + 125 mg
    s = s.replace(/\s*\+\s*/g,' + ');
    return s;
  }

  function splitCamelPascal(s){
    // Insert space between lowerUpper and ABBRWord boundaries
    s = s.replace(/([a-z])([A-Z])/g,'$1 $2');
    s = s.replace(/([A-Z]{2,})([A-Z][a-z])/g,'$1 $2');
    // break sequences like "drugnameINJECTIONIP" -> "drugname INJECTION IP"
    s = s.replace(/([a-zA-Z])([A-Z]{2,})/g,'$1 $2');
    return s;
  }

  function fixFormsAndTokens(s){
    // ensure a space between form tokens if stuck to next letters: "TabletsIP" -> "Tablets IP"
    FORMS.forEach(function(f){
      const re = new RegExp('\\b(' + f + ')([A-Za-z0-9\\.])','ig');
      s = s.replace(re, function(_, a, b){ return a + ' ' + b; });
    });
    // filmcoated -> film-coated (improves readability), entericcoated -> enteric-coated
    s = s.replace(/\bfilmcoated\b/ig,'film-coated');
    s = s.replace(/\bentericcoated\b/ig,'enteric-coated');
    s = s.replace(/\btabletss?\b/ig,'tablets');
    // common mistake: "mgfilm-coated" or " mg film coated"
    s = s.replace(/mg\s*film[- ]?coated/ig,'mg film-coated');
    // split tokens like "IP" "I.P." "BP" etc.
    s = s.replace(/\bI\.?P\.?\b/ig,'IP');
    s = s.replace(/\bB\.?P\.?\b/ig,'BP');
    s = s.replace(/\bS\.?R\.?\b/ig,'SR');
    s = s.replace(/\bE\.?R\.?\b/ig,'ER');
    s = s.replace(/\bC\.?R\.?\b/ig,'CR');
    return s;
  }

  function tidySpaces(s){
    s = s.replace(/\s{2,}/g,' ');
    s = s.replace(/\s+([,.;\)\]])/g,'$1');
    s = s.replace(/([\(\[\{])\s+/g,'$1 ');
    s = s.trim();
    return s;
  }

  function capitalizeStart(s){
    if(!s || s.length===0) return s;
    return s.charAt(0).toUpperCase() + s.slice(1);
  }

  function cleanOne(original){
    let s = String(original);

    s = normalizeMicroSigns(s);
    s = spaceAroundPunct(s);
    s = splitLettersNumbers(s);
    s = fixUnits(s);
    s = splitCamelPascal(s);
    s = fixFormsAndTokens(s);
    s = tidySpaces(s);

    // Special fixes for parentheses content like "(100 mg+50 mg)" -> "(100 mg + 50 mg)"
    s = s.replace(/\(\s*([^\)]+)\s*\)/g, function(_, inner){
      inner = inner.replace(/\s*\+\s*/g,' + ');
      return '(' + inner.trim() + ')';
    });

    // Some final heuristics:
    s = s.replace(/\s*\/\s*/g,' / ');
    s = s.replace(/\s*\+\s*/g,' + ');
    s = s.replace(/\s*\-\s*/g,' - ');

    s = capitalizeStart(s);
    return s;
  }

  // Run on your array:
  if(typeof allMedsCombined === 'undefined' || !Array.isArray(allMedsCombined)){
    console.error('Cannot find allMedsCombined array in scope. Paste this after your array definition.');
    return;
  }

  const cleaned = allMedsCombined.map(function(orig){
    const nameClean = cleanOne(orig);
    // Extract strength/form from cleaned name
    const strengthMatch = nameClean.match(/(\d+(?:\.\d+)?\s?(?:mg|g|gm|ml|mcg|µg|%|iu|iu\/ml))/i);
    const formMatch = nameClean.match(new RegExp('\\b(' + FORMS.join('|') + ')\\b','i'));
    return {
      original: orig,
      name: nameClean,
      strength: strengthMatch ? strengthMatch[1] : '',
      form: formMatch ? formMatch[1].toLowerCase() : ''
    };
  });

  // place cleaned dataset in window for immediate use
  window.meds_10000_cleaned = cleaned.map(function(o){ return { name: o.name, strength: o.strength, form: o.form }; });

  // also replace the allMedsCombined array with cleaned strings if you prefer (comment/uncomment accordingly)
  // window.allMedsCombined_cleanedStrings = cleaned.map(o => o.name);

  // Print a diff-ish sample for quick QA (first 60 items)
  console.log('=== First 60 cleaned entries (original -> cleaned) ===');
  cleaned.slice(0,60).forEach(function(o,i){
    console.log(i+1 +'.', 'ORIG:', o.original);
    console.log('    CLEANED:', o.name);
  });

  // If you want the full cleaned JS array text to copy-paste, uncomment below to log it:
  // console.log('FULL_CLEANED_ARRAY = [');
  // window.allMedsCombined_cleanedStrings.forEach(s => console.log('  "' + s.replace(/"/g,'\\"') + '",'));
  // console.log('];');

  // Expose helper to produce full copyable JS string
  window.getCleanedArrayText = function(){
    return 'const allMedsCombined = [\\n' +
      window.allMedsCombined_cleanedStrings.map(function(s){ return '  "' + s.replace(/"/g,'\\"') + '",'; }).join('\\n') +
      '\\n];';
  };

})();
